### ISSUE TITLE
Add key and values on the SecretProviderClass directly

### ISSUE THREAD

**Issue by rshiva777** [kubernetes-sigs/secrets-store-csi-driver#1027]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

At present, i am able to mount the secrets using the csi-secret-store driver from vault.

There is a usecase where we need to add url field manually on secretproviderclass, only username and password need to be fetched from the vault

```
example:

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-credentials
spec:
  provider: vault
  secretObjects:
  - data:
   - key: url
     value: http://test.github.com
    - key: user
      objectName: user
    - key: password
      objectName: password
    secretName: dbpass
    type: Opaque
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "csi-kv"
    objects: |
      - objectName: "user"
        secretPath: "kv/app"
        secretKey: "user"
      - objectName: "password"
        secretPath: "kv/db"
        secretKey: "password"
```

In the above yaml, i added an object which take user input key and value, other objects take values from vault secret manager.

```
   - key: url
     value: http://test.github.com  ## this should be the direct user input, where user enter the value directly on crd
    - key: user
      objectName: user                   ## this is the secret fetched from vault secret manager
```

Can this be acheived

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):  v1.2.3
- Kubernetes version: (use `kubectl version`): 1.20.5
