### ISSUE TITLE
SPC with synced K8S Secret populating the secret with an "empty" cert

### ISSUE THREAD

**Issue by jroggeman** [kubernetes-sigs/secrets-store-csi-driver#1057]
**What steps did you take and what happened:**
We have a fairly standard app consisting of a Deployment, Service, SPC w/ synced Secrets, and Ingress. The SPC is mounted on the deployment pods and is syncing secrets that the ingress references as TLS certs. However, the synced secrets' data sections have only empty values:
```yaml
data:
  tls.crt: ""
  tls.key: <base64-encoded "---BEGIN PRIVATE KEY---\n---END PRIVATE KEY---". Just those lines, no content.>
```

**What did you expect to happen:**
The referenced certificate to be synced successfully

**Anything else you would like to add:**
So as described above, we have an app with a fairly standard setup of ingresses, and when deploying it, we're hitting a rather strange scenario where it's syncing an "empty" secret. Specs included below, as they're rather large - in essence, an SPC has a _somewhat_ large (about 8) set of synced objects it's using for creating a set of ingress secrets. the SPC is mounted on the pod and works fine - the pod starts up successfully - but the secrets that are synced are invalid.

In particular, the equivalent of ` notebook-instance-proxy-managed-ingress-ssl-synced` in our specs is empty, with the contents I pasted above:
```yaml
data:
  tls.crt: ""
  tls.key: <base64-encoded "---BEGIN PRIVATE KEY---\n---END PRIVATE KEY---">
```

I've checked through a wide variety of logs from both csi and azure components - there were no error logs, and all logs mentioning the pod name or SPC indicated nothing went wrong or differently than any of our other deployments that use CSI Driver.

It doesn't appear to be like a one off transient issue, as deployments of that same build to a different namespace (for PR gates) also have the same issue. deleting and redeploying the app to recreate the secrets has resulted in the same issue as well. We're kind of at a loss for what might be going on.

The only thing that's stood out to me so far is that the SPC in question has a relatively large number of separately-synced objects.

One other notable fact might be that we've migrated from self-hosted to AKS-hosted CSI driver, in case there might be some strangeness with that handover.

Spec note - these approximate the shape of what we're doing with some stuff omitted for brevity or security. I can privately send over a more complete set of files if needed.
```yaml
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  # [... Truncated ...]
spec:
  progressDeadlineSeconds: 600
  replicas: 10
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: notebook-instance-proxy
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: notebook-instance-proxy
        app-web: notebook-instance-proxy
      namespace: vienna-master
    spec:
      containers:
        # [ ... Truncated ... ]
        volumeMounts:
        - mountPath: /app/secrets/
          name: secrets-volume
          readOnly: true
      # [ ... Truncated ... ]
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          nodePublishSecretRef:
            name: notebook-instance-proxy-kv-creds
          readOnly: true
          volumeAttributes:
            secretProviderClass: notebook-instance-proxy-secretprovider
        name: secrets-volume

---
# SPC
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: notebook-instance-proxy-secretprovider
  namespace: vienna-master
spec:
  parameters:
    cloudEnvFileName: /
    cloudName: AZUREPUBLICCLOUD
    keyvaultName: <ommitted>
    objects: |
      array:
        - |
          objectName: "cert-1"
          objectAlias: "cert-1"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "cert-2"
          objectAlias: "cert-2"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "cert-3"
          objectAlias: "cert-3"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "cert-4"
          objectAlias: "cert-4"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "cert-5"
          objectAlias: "cert-5"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "cert-6"
          objectAlias: "cert-6"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "cert-7"
          objectAlias: "cert-7"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "cert-8"
          objectAlias: "cert-8"
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
        - |
          objectName: "secret-1"
          objectAlias: "secret-1"
          objectType: secret
        - |
          objectName: "secret-2"
          objectAlias: "secret-2"
          objectType: secret
        - |
          objectName: "secret-3"
          objectAlias: "secret-3"
          objectType: secret
        - |
          objectName: "secret-4"
          objectAlias: "secret-4"
          objectType: secret
        - |
          objectName: "secret-5"
          objectAlias: "secret-5"
          objectType: secret
        - |
          objectName: "secret-6"
          objectAlias: "secret-6"
          objectType: secret
    tenantId: <ommitted>
  provider: azure
  secretObjects:
  - data:
    - key: tls.crt
      objectName: cert-1
    - key: tls.key
      objectName: cert-1
    secretName: notebook-instance-proxy-managed-ingress-ssl-synced
    type: kubernetes.io/tls
  - data:
    - key: tls.crt
      objectName: cert-2
    - key: tls.key
      objectName: cert-2
    secretName: notebook-instance-proxy-ingress-ssl-synced
    type: kubernetes.io/tls
  - data:
    - key: tls.crt
      objectName: cert-3
    - key: tls.key
      objectName: cert-3
    secretName: notebook-instance-proxy-modern-ingress-ssl-synced
    type: kubernetes.io/tls
  - data:
    - key: tls.crt
      objectName: cert-4
    - key: tls.key
      objectName: cert-4
    secretName: notebook-instance-proxy-managed-ms-ingress-internal-ssl-synced
    type: kubernetes.io/tls
  - data:
    - key: tls.crt
      objectName: cert-5
    - key: tls.key
      objectName: cert-5
    secretName: notebook-instance-proxy-nodes-ingress-ssl-synced
    type: kubernetes.io/tls
  - data:
    - key: tls.crt
      objectName: cert-6
    - key: tls.key
      objectName: cert-6
    secretName: notebook-instance-proxy-certapi-ingress-ssl-synced
    type: kubernetes.io/tls
  - data:
    - key: secret-1
      objectName: secret-1
    - key: secret-2
      objectName: secret-2
    - key: secret-3
      objectName: secret-3
    - key: secret-4
      objectName: secret-4
    - key: secret-5
      objectName: secret-5
    - key: secret-6
      objectName: secret-6
    secretName: notebook-instance-proxy-synced
    type: Opaque

---

# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # [... ommitted ...]
  generation: 48
  name: notebook-instance-proxy-ingress
  namespace: vienna-master
spec:
  rules:
  - host: auth.master.instances.azureml-test.ms
    http:
      paths:
      - backend:
          service:
            name: notebook-instance-proxy
            port:
              number: 443
        path: /
        pathType: Prefix
  - host: '*.master.instances.azureml-test.net'
    http:
      paths:
      - backend:
          service:
            name: notebook-instance-proxy
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - '*.master.instances.azureml-test.net'
    secretName: notebook-instance-proxy-managed-ingress-ssl-synced
  - hosts:
    - auth.master.instances.azureml-test.ms
    - '*.master.instances.azureml-test.ms'
    secretName: notebook-instance-proxy-modern-ingress-ssl-synced
```

**Which provider are you using:**
Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): AKS-managed
- Kubernetes version: (use `kubectl version`): 1.23
