### ISSUE TITLE
Create k8s secret with only some key of original secret

### ISSUE THREAD

**Issue by neottil** [kubernetes-sigs/secrets-store-csi-driver#1078]
I've secret AWS like this 
```
{a:1, b:2, c:3, ...}
```
and I would like to create k8s secret with the "a" and "b" key/value pairs.

At the moment I've the possibility to map all AWS secret pairs in a kubernetes secret key with this configuration:

```YAML
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secret-provider
spec:
  provider: aws
  secretObjects:
  - secretName: k8s-secret
    type: Opaque
    data:
    - key: secret
      objectName: my-aws-secret
  parameters:
    objects: |
      - objectName: aws-secret
        objectAlias: my-aws-secret
        objectType: secretsmanager
```
In this way k8s-secret is like
```
{
  secret: {a:1,b:2,c:3,...}
}
```
Like jmesPath for mapping aws secret pairs in files, I would like to have chance to create kubernetes secret by mapping pairs that I want to use in kubernetes. Maybe the AWS secret contains other pairs that I don't need in kubernetes secret. So the kubernetes secret that I want to obtains is like:
```
{a:1, b:2}
```
With this secret I can mapping env variable in my deployments

The optimal solution for me would be to have the possibility to map every single key in the k8s secret with the secret and the key of origin like this:
```YAML
data:
    - key: k8s-user
      objectName: aws-secret-1
      objectKey: user
    - key: k8s-user2
      objectName: aws-secret-2
      objectKey: user
```

**Environment:**
- Kubernetes version: 1.21:
