### ISSUE TITLE
Potential Deadlock when k8s evicts pods using CSI

### ISSUE THREAD

**Issue by peter-glotfelty** [kubernetes-sigs/secrets-store-csi-driver#1079]
**What steps did you take and what happened:**

We seem to have deadlocked a node/several pods because of the secrets-store-csi-driver. To forcibly re-execute a MutatingAdmissionController, we restarted a large % of deployments + ds in our cluster. During the shuffle things got moved around, and we ended up in this situation:

- The new csi-driver pod wanted to come up, but couldn't because the node was fully scheduled
- Fortunately, it runs at a very high priority so several existing pods were evicted.
- Unfortunately, these pods chosen for eviction were blocked from terminating b/c they use secrets-store-csi and they couldn't unmount their volumes

```
E1004 23:42:12.134454    6112 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/csi/7200b312-4ef1-4838-a8ad-a582d4550af8-<volume-name> podName:7200b312-4ef1-4838-a8ad-a582d4550af8 nodeName:}" failed. 
No retries permitted until 2022-10-04 23:43:16.134434708 +0000 UTC m=+446720.836217921 (durationBeforeRetry 1m4s). 
Error: UnmountVolume.TearDown failed for volume "<volume-name>" (UniqueName: "kubernetes.io/csi/7200b312-4ef1-4838-a8ad-a582d4550af8-<volume-name>") pod "7200b312-4ef1-4838-a8ad-a582d4550af8" (UID: "7200b312-4ef1-4838-a8ad-a582d4550af8") 
: kubernetes.io/csi: Unmounter.TearDownAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers
```
- The system got stuck in this state until we deleted the node a few hours later.

**What did you expect to happen:**

The system could ideally self-heal in this state, or try evicting different pods to free up capacity.

**Which provider are you using:**
- Azure Key Vault w/ AKS

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): `driver:v1.2.3`
- Kubernetes version: (use `kubectl version`): `1.23`

**Comment by mattjamesaus** [comment]
I'm wondering here if we can add a preStop sleep as an option for the helm chart? That would potentially allow us to let the driver sleep for 30s (or whatever time is required) in order to make sure other pods potentially leveraging the the driver to properly shutdown?

**Comment by wackxu** [comment]
Has this problem been solved? Any suggestions to avoid this problem?

**Comment by wackxu** [comment]
@mattjamesaus Could you give some suggestions how to fix this deadlock?

**Comment by mattjamesaus** [comment]
@wackxu so we're using flux in our clusters and i dropped this in months ago and the problem went away.

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
spec:
  interval: 5m
  chart:
    spec:
      version: "1.2.x"
      chart: secrets-store-csi-driver
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
      interval: 60m
  values:
    ## Install RBAC roles and bindings required for K8S Secrets syncing if true
    syncSecret:
      enabled: true
    ## Enable secret rotation feature [alpha]
    enableSecretRotation: false
    ## Secret rotation poll interval duration
    rotationPollInterval: 3600s
    linux:
      priorityClassName: "system-node-critical"
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: DaemonSet
            apiVersion: apps/v1
            metadata:
              name: secrets-store-csi-driver
              namespace: kube-system
            spec:
              template:
                metadata:
                  annotations:
                    "cluster-autoscaler.kubernetes.io/enable-ds-eviction": "false"
                spec:
                  containers:
                    - name: node-driver-registrar
                      lifecycle:
                        preStop:
                          exec:
                            command: ["sleep", "30"]
                    - name: secrets-store
                      lifecycle:
                        preStop:
                          exec:
                            command: ["sleep", "30"]
                    - name: liveness-probe
                      lifecycle:
                        preStop:
                          exec:
                            command: ["sleep", "30"]
                  terminationGracePeriodSeconds: 60
```
