### ISSUE TITLE
Vault provider not found , inter cluster connection .

### ISSUE THREAD

**Issue by pratiyush05** [kubernetes-sigs/secrets-store-csi-driver#1101]
Versions in use-
CSI driver - 1.2.4
Vault provider - 1.2.0

Description 
Trying to fetch vault provider from CSI driver present on different kubernetes cluster .Clusters are connected by service mesh . 
Vault + Vault-provider present in 'cluster-A' .
CSI-driver + SecretProviderClass + POD present in 'cluster-B' .
Vault is accessible from cluster-B .

Error obtained -
`FailedMount	MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod <application-namespace>/<application-POD-name>, err: error connecting to provider "vault": provider not found: provider "vault"`

When this error occurred -
On deploying POD which was requesting CSI volume mount . 

SecretProviderClass.yaml used - 
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: XYZ
  labels:
    serviceAccountName: XYZ
    namespace: prod
spec:
  provider: vault
  parameters:
    vaultAddress: <vault address present in cluster -A>
    objects: |
      - objectName: "db-user"
        secretPath: "path/to/secret/"
        secretKey: "password" 
```

Is there any possible way to make CSI driver present in cluster-B establish a connection with Vault-provider in Cluster-A ?
