### ISSUE TITLE
Possibility to add additional static string date to the created secret with CSI driver

### ISSUE THREAD

**Issue by AswinT22** [kubernetes-sigs/secrets-store-csi-driver#1153]
At the moment the created secret can only contain values that have been fetched by the CSI driver. In use cases when we want to add some non-sensitive data as part of the secret we had to add those to the vault and fetch them along with the sensitive data. 

I want to go from this 
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: my-provider
spec:
  provider: vault 
  parameters:
    objects: |
      - objectName: "username"
        secretPath: "secret/data"
        secretKey: "username_from_vault"
      - objectName: "url"
        secretPath: "secret/data"
        secretKey: "url_from_vault"
      - objectName: "password"
        secretPath: "secret/data"
        secretKey: "password_from_vault"                    
  secretObjects:                              
    - data:
        - key: PASSWORD                        
          objectName: password      
        - key: USERNAME                        
          objectName: username
        - key: URL                        
          objectName: url                
      secretName: credentials    
      type: Opaque
```

to this 

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: my-provider
spec:
  provider: vault 
  parameters:
    objects: |
      - objectName: "password"
        secretPath: "secret/data"
        secretKey: "password_from_vault"                    
  secretObjects:                              
    - data:
        - key: PASSWORD                        
          objectName: password 
      stringData:     # data under this will be added to the secret object along with the retrieved secrets 
        - key: USERNAME                        
          value: myusername
        - key: URL                        
          value: myurl                
      secretName: credentials    
      type: Opaque
```
