### ISSUE TITLE
Unable to rotate environment varibale when using stakater/Reloader

### ISSUE THREAD

**Issue by sidhanshumahajan** [kubernetes-sigs/secrets-store-csi-driver#1180]
@aramase  Can You plz look into this

[**What steps did you take and what happened: **
1) I have installed CSI driver and mount secret as volume and then also install stakater/Reloader using helm chart but when i update secrets in key vault it get reflected in volume mount but not in environment variable of pod.

For Reference I have used this blog 
link( https://roykim.ca/2022/11/13/how-to-reload-an-env-variable-syncd-to-a-mounted-azure-key-vault-secret/)

**What did you expect to happen: **
Expected behavior is that that pod environment variable also got updated without any need to redeploy my pod.

**Which provider are you using: **
 Azure Key Vault

- Secrets Store CSI Driver version: (1.26.2):
- azure aks version: 1.24

Below are the deployment files which I have used:

###Pod File
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox2
  annotations:
      secret.reloader.stakater.com/reload: "true"
  labels:
    app: busybox
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: busybox
          image: registry.k8s.io/e2e-test-images/busybox:1.29-4
          command:
            - "/bin/sleep"
            - "10000"
          env:
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: AZURE-CLIENT-ID
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: my-secret1
                  key: AZURE-TENANT-ID
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-sync"
            nodePublishSecretRef:
              name: secrets-store-creds

------------------------------------------
##ServiceProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure
  secretObjects:                                  # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - secretName: my-secret
      type: Opaque
      data:
        - objectName: AZURE-CLIENT-ID                 # name of the mounted content to sync. this could be the object name or object alias. The mount is mandatory for the content to be synced as Kubernetes secret.
          key: AZURE-CLIENT-ID
    - secretName: my-secret1
      type: Opaque
      data:
        - objectName: AZURE-TENANT-ID                 # name of the mounted content to sync. this could be the object name or object alias. The mount is mandatory for the content to be synced as Kubernetes secret.
          key: AZURE-TENANT-ID
  parameters:
    usePodIdentity: "false"                       # [OPTIONAL] if not provided, will default to "false"
    keyvaultName: "vault38733"                        # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: AZURE-CLIENT-ID
          objectType: secret                      # object types: secret, key or cert
          objectAlias: AZURE-CLIENT-ID
        - |
          objectName: AZURE-TENANT-ID
          objectType: secret                      # object types: secret, key or cert
          objectAlias: AZURE-TENANT-ID
    tenantId: "<tenantId>"                               # the tenant ID of the KeyVault
```
