### ISSUE TITLE
 failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by 13567436138** [kubernetes-sigs/secrets-store-csi-driver#1226]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
secret/csi/appProject-helm.yaml

kubectl apply -f appProject-helm.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: csi
spec:
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  sourceRepos:
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  destinations:
    - server: https://192.168.229.153:6443
      namespace: kube-system
    - server: https://192.168.229.156:6443
      namespace: kube-system
```

secret/csi/appset-secrets-store-csi-driver.yaml

kubectl apply -f appset-secrets-store-csi-driver.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secrets-store-csi-driver
spec:
  generators:
  - list:
      elements:
        - url: https://192.168.229.153:6443
          cluster: cluster1
        - url: https://192.168.229.156:6443
          cluster: cluster2
  template:
    metadata:
      name: '{{cluster}}-csi'
    spec:
      project: csi
      source:
        repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
        targetRevision: 1.3.3
        chart: secrets-store-csi-driver
        helm:
          values: |
            linux:
              image:
                repository: registry.cn-hangzhou.aliyuncs.com/hxpdocker/driver
              crds:
                image:
                  repository: registry.cn-hangzhou.aliyuncs.com/hxpdocker/driver-crds
              driver:
                resources:
                  requests:
                    cpu: 5m
                    memory: 10Mi
              registrarImage:
                repository: registry.cn-hangzhou.aliyuncs.com/hxpdocker/csi-node-driver-registrar
              livenessProbeImage:
                repository: registry.cn-hangzhou.aliyuncs.com/hxpdocker/livenessprobe
            syncSecret:
              enabled: true
            enableSecretRotation: true   
      destination:
        server: '{{url}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
```

```
[root@member1-153 ~]# kubectl get crd|grep csi
secretproviderclasses.secrets-store.csi.x-k8s.io            2023-04-22T08:12:25Z
secretproviderclasspodstatuses.secrets-store.csi.x-k8s.io   2023-04-22T08:12:25Z
```

## Install External Secret Providers

```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: csi-spc
spec:
  provider: vault
  secretObjects:
  - secretName: cred
    type: Opaque
    data: 
    - objectName: password
      key: password
    - objectName: username
      key: username
  parameters:
    roleName: "myapp"
    vaultAddress: https://192.168.229.153:6443
    objects:  |
      - secretPath: "kv/data/cred"
        objectName: "username"
        secretKey: "username"
      - secretPath: "secret/data/foo1"
        objectName: "password"
        secretKey: "passowrd"
```

```
kind: Pod
apiVersion: v1
metadata:
  name: secrets-store-inline
spec:
  containers:
  - image: nginx
    name: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "csi-spc"
```

```
export VAULT_ADDR=http://192.168.229.148:31758
 

vault policy write app app-policy.hcl

[root@mycompany secret]# cat app-policy.hcl 
path "kv/*" {
  capabilities = ["read"]
}

vault auth enable kubernetes

cat  .kube/config |grep certificate-authority-data | awk -F ' ' '{print $2}' |base64 -d > ca.crt

vault write auth/kubernetes/config \
   kubernetes_host=https://192.168.229.153:6443 \
   kubernetes_ca_cert=@ca.crt \
   disable_local_ca_jwt=true


vault write auth/kubernetes/role/myapp \
   bound_service_account_names=default \
   bound_service_account_namespaces=demo \
   policies=app \
   ttl=1024h
   
   
vault kv put kv/cred username=mark password=123


```

secret/argocd-vault-plugin/ap-clusterResourceWhitelist.yaml

kubectl apply -f ap-clusterResourceWhitelist.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  sourceRepos:
    - https://gitee.com/hxpgit/argocd.git
  destinations:
    - server: https://192.168.229.153:6443
      namespace: demo
      name: cluster1
    - server: https://192.168.229.156:6443
      namespace: demo
```

secret/app-csi.yaml

kubectl apply -f app-csi.yaml -n argocd

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    namespace: demo
    name: cluster1
  source:
    repoURL: https://gitee.com/hxpgit/argocd.git
    path: demo1/secretManager/csi
    targetRevision: HEAD 
  project: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

```
  Warning  FailedMount  0s (x4 over 15s)  kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod demo/secrets-store-inline, err: rpc error: code = Unknown desc = error making mount request: failed to login: Post "https://192.168.229.153:6443/v1/auth/kubernetes/login": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]
vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):v1.3.3
- Kubernetes version: (use `kubectl version`):1.23.1
