### ISSUE TITLE
Automatic secrets reloading upon update in the external secrets store

### ISSUE THREAD

**Issue by dmeytin** [kubernetes-sigs/secrets-store-csi-driver#125]
There are many use-cases when secret/certificate is being updated in the KeyVault. The most prominent use-case is the rotation flow. Fortunately, KeyVault takes care of certificates and Azure Storage SAS rotations. When new secret/certificate has been created, the running pod will not start to utilize it till the restart. Only at restart the tmpfs will be created with renewed secrets. 
In most cases (but not all cases) the old secret will continue to work and there is a plenty of time for pod being restarted.
Everything goes complicated when there are many services that utilize many secrets. It's pretty normal situation when single cluster serves hundreds of services and thousands of secrets. 
Synchronization at scale brings a lot of mess into cluster operation.

I would like to request a new feature to secrets store to reload secrets upon update. Since many client's implementations do not support live reload, the pod restart will be the ideal solution.

**Comment by dmeytin** [comment]
@ritazh

**Comment by sudharsan89** [comment]
This is very similar to t[his feature request](https://github.com/Azure/kubernetes-keyvault-flexvol/issues/146) for a similar project using KeyVault Flex Volume.  This would also help with the azure emergency certificate rotation initiative.

**Comment by ritazh** [comment]
Here are some design components to consider:
1. A reconciler that periodically calls the provider binary to get latest. Reconciler is a sidecar of the csi driver.
2. Provider binary compares current version with latest version from secrets store. Updates content in mounted file on host. Returns latest version to the driver.
3. Reconciler updates the `secretsproviderclass` object by updating the `objectVersion` field as part of the `secretObjects` field in the spec. (NOTE: this is a new property introduced in #186)
```yaml
  secretObjects:
  - data:
    - key: pwd
      objectName: foo
      objectVersion: 4484848
    - key: username
      objectName: foo1
      objectVersion: 96885
    secretName: foosecret
    type: Opaque
```
4. A separate reconciler #188 that watches on changes in `secretsproviderclass` object will reconcile the latest data to the corresponding K8s secret object.

cc @aramase @bdlb77 @paulbouwer

**Comment by ritazh** [comment]
Per today's standup:
For 3. we can consider adding the objectVersion to the status field of the object to avoid user overriding the object direclty.
```yaml
spec:
  parameters:
    objects: |
      array:
        - |
          objectPath: "/foo"
          objectName: "bar"
          objectVersion: ""
        - |
          objectPath: "/foo1"
          objectName: "bar"
          objectVersion: ""
    roleName: example-role
    vaultAddress: http://10.0.219.186:8200
    vaultSkipTLSVerify: "true"
  provider: vault
  secretObjects:
  - data:
    - key: pwd
      objectName: foo
    - key: username
      objectName: foo1
    secretName: foosecret
    type: Opaque
status:
  versions:
  - objectName: foo
       objectVersion: 58584884
  - objectName: foo1
       objectVersion: 979685
  byPod:
  - id: 07b8b844-797d-4fa5-9638-e93c4e5f467c
    namespace: default
  - id: 101c3595-1863-4571-8b40-d32d51691335
    namespace: default
```

**Comment by aramase** [comment]
As discussed on today's standup:

One thing to consider here - reconciler runs as a sidecar in the driver. This means each reconciler watches for changes in all the `SecretProviderClass` custom resources. This could potentially be a problem when there are large # of custom resources with a relative large cluster. 

Possible solution - 

Driver can label/annotate the `SecretProviderClass` object while updating the `status.byPod` field. The label would be `<nodeName>: true`. The reconciler sidecar can be configured to watch on `SecretProviderClass` custom resources that contain the label. The label approach needs to be taken because there is no filtered watch possible with CRDs and also because CRDs here aren't tied to a node. By watching only on `SecretProviderClass` that contain the node label, we can accomplish the filtered watch and should be able to scale well with increase in # of nodes or custom resources.

**Comment by bdlb77** [comment]
Another consideration:

A user may define a specific `objectVersion` for a secret that they would want to be constant. When a new secret gets rotated in a Vault,  that constant secret could be updated with a new version thus overriding a specific `objectVersion` that they expect to be constant. 

**Some Possible Solutions**
1. When secrets are rotated in a Vault, overwrite all existing secrets in the cluster. We must make note that defining an `objectVersion` in the first deployment may be overwritten in a secret rotation. 
2. Only watch secrets that don't have a defined `objectVersion`. We could add an extra property to `version` object such as `isVersionDefined: false` (This would be defined by if an original `objectVersion` was defined during first deployment).  Once new secret versions are fetched from a vault, update the `status` property on the `secretproviderclass` by taking a map of the current `status.versions` and update each value where `isVersionDefined: false` 
example:
```yaml
spec:
  parameters:
    objects: |
      array:
        - |
          objectPath: "/foo"
          objectName: "bar"
          objectVersion: "58584884"
        - |
          objectPath: "/foo1"
          objectName: "bar"
          objectVersion: ""
    ...

status:
  versions:
  -  objectName: foo
     objectVersion: 58584884
     isVersionDefined: true
  - objectName: foo1
     objectVersion: 979685
     isVersionDefined: false
```
