### ISSUE TITLE
Spawn k8s secret without volume mount

### ISSUE THREAD

**Issue by Stiuil06** [kubernetes-sigs/secrets-store-csi-driver#1253]
**Describe the solution you'd like**
It would be nice to be able to create K8S secret without requiring mounting as a pod volume. I mean this:
```yaml
spec:
 volumes:
  - name: secret-name
     csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
       secretProviderClass: secret-name-csi
```

**Anything else you would like to add:**
This is a popular pattern that chart's providers allows to deliver the secret directly via value:
```yaml
licenseKey: secretPasswordHere
```
or they allows to provide values pointing to the secret in which the secret value is located:
```yaml
customSecretName: custom-secret-name #Name of the Secret object where the license key is stored
customSecretLicenseKey: value-key #Key in the Secret object where the license key is stored
```

P.S.
Im using Argo CD and I want to run this [chart](https://github.com/newrelic/helm-charts/tree/master/charts/nri-bundle) in GitOPS approach.

**Environment:**
- Secrets Store CSI Driver version: secrets-store-csi-driver-provider-azure v1.4.0
- Kubernetes version:
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.23.12
