### ISSUE TITLE
can't set objectAlias to other names

### ISSUE THREAD

**Issue by ozbillwang** [kubernetes-sigs/secrets-store-csi-driver#1313]
**What steps did you take and what happened:**

I have to set `objectAlias` to `secretalias`,  if I choice to other names, secret is not created.

```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akvprovider-demo
  namespace: test-only
spec:
  provider: azure
  secretObjects:
  - secretName: foosecret
    type: Opaque
    data:
    - objectName: SECRET_1
      key: ADMIN-PASSWORD
    # - objectName: secretalias
    #    key: ADMIN-PASSWORD
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "xxxx-xxxx-xxxx-xxxx-xxxxxxxx"
    keyvaultName: keycloak-prod-secret
    objects: |
      array:
        - |
          objectName: ADMIN-PASSWORD
          objectType: secret
          objectAlias: SECRET_1
          objectVersion: ''
        # - |
        #   objectName: ADMIN-PASSWORD
        #   objectType: secret
        #   objectAlias: secretalias
        #   objectVersion: ''
    tenantId:  "xxxx-xxxx-xxxx-xxxx-xxxxxxxx"
```
So if I switch to use `secretalias` in `objectAlias`, after I apply it, the secret `foosecret` created immediately. But if I change the name to others, such as `secretalias01`, `SECRET_1`, no secret is created.

**What did you expect to happen:**

after apply above yaml file, a secret `foosecret` need be created automatically.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**

aks-secrets-store-csi-driver
aks-secrets-store-provider

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 
```
    Image:         mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.8.0
    Image:         mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v1.3.4
    Image:         mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.10.0
```
- Kubernetes version: (use `kubectl version`):

```
kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.26.3
```
