### ISSUE TITLE
Secrets are not created when syncing to mounted secret files and environment variables not created

### ISSUE THREAD

**Issue by evertonspader-tomtom** [kubernetes-sigs/secrets-store-csi-driver#1317]
I can't get the secrets loaded from Azure Key Vault to sync as Kubernetes secrets and eventually as an environment variable. We have deployed the `secrets-store-csi-driver` and `csi-secrets-store-provider-azure` with Helm and I have set `secrets-store-csi-driver.syncSecret.enabled` to `true` in both charts.

This is my test configuration: 

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: busybox
  namespace: busybox
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-kv-test
  namespace: busybox
spec:
  provider: azure
  secretObjects:
    - secretName: test-api-key
      type: Opaque
      data:
        - objectName: test-api-key
          key: api-key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: <clientID>
    tenantId: <tenantID>
    keyvaultName: "kv-test-dev"
    objects: |
      array:
        - |
          objectName: test-api-key
          # objectAlias: test-api-key           # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret              # object types: secret, key or cert. For Key Vault certificates, refer to https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/getting-certs-and-keys/ for the object type to use
---
kind: Pod
apiVersion: v1
metadata:
  namespace: busybox
  name: busybox
spec:
  serviceAccountName: busybox
  containers:
    - name: busybox
      image: k8s.gcr.io/e2e-test-images/busybox:1.29
      command:
        - "/bin/sleep"
        - "10000"
      env:
        - name: TEST_API_KEY
          valueFrom:
            secretKeyRef:
              name: test-api-key
              key: api-key
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: spc-kv-test
```

If I apply the above configuration **without** the environment variable part, the container is created successfully and I can see the mounted file:

```shell
kubectl exec busybox -- cat /mnt/secrets-store/test-api-key
0Jqd4PEkmZHsZXSvxaBmI2fqq8Pz8jsSPv_5mw-
```

When I try to map it to a Kubernetes secret and then an environment variable with the above configuration, the container fails to start with the following error:

```shelll
Events:
  Type     Reason                Age                From                          Message
  ----     ------                ----               ----                          -------
  Normal   Scheduled             11s                default-scheduler             Successfully assigned busybox/busybox to aks-default-99369892-vmss000003
  Normal   Pulled                10s (x2 over 11s)  kubelet                       Container image "k8s.gcr.io/e2e-test-images/busybox:1.29" already present on machine
  Warning  Failed                10s (x2 over 11s)  kubelet                       Error: secret "test-api-key" not found
  Warning  FailedToCreateSecret  0s (x12 over 11s)  csi-secrets-store-controller  timed out waiting for the condition
```

I have tried to follow the examples from the [documentation](https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret) but I can't seem to spot the error in the configuration.
