### ISSUE TITLE
Feat: Add support to define (overwrite) SecurityContext

### ISSUE THREAD

**Issue by cbugneac-nex** [kubernetes-sigs/secrets-store-csi-driver#1437]
**Describe the solution you'd like**
One of requirements from our Cyber security team is to drop capabilities where possible to improve security posture (reduce attack surface) for containers running in k8s.

In values.yaml file to define something like (example):
```yaml
...
securityContext:
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
```

**Anything else you would like to add:**
At the moment, this is not possible as it's hardcoded https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml#L113

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1.4.1
- Kubernetes version: (use `kubectl version`): EKS version 1.26.12
