### ISSUE TITLE
pod terminating error When deleting a pod volume mounted by secret csi driver

### ISSUE THREAD

**Issue by kobayashita** [kubernetes-sigs/secrets-store-csi-driver#1582]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

- I'm using secret csi provider (eg, keycloak pod)
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keycloak-secrets
  namespace: cluster
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "keycloak"
          objectType: "secretsmanager"
          jmesPath:
              - path: "KC_LOG_LEVEL"
                objectAlias: "KC_LOG_LEVEL"
  secretObjects:
    - secretName: keycloak-secret
      type: Opaque
      data:
        - key: KC_LOG_LEVEL
          objectName: KC_LOG_LEVEL
```
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  template:
    spec:
      containers:            
          envFrom:
            - secretRef:
                name: keycloak-secret
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "keycloak-secrets"
```
- first delete secret csi driver pod, then delete keycloak(mounted volume) pod. But the following error occurred.
    pod status is terminating. I cannot delete pod.
```
apiVersion: v1
kind: Pod
metadata:
spec:
status:
  containerStatuses:
  - containerID: ***
    image: ***
    imageID: ***
    lastState: {}
    name: keycloak
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: ***
        exitCode: 143
        finishedAt: "2024-07-26T07:10:01Z"
        reason: Error
        startedAt: "2024-07-26T07:09:08Z"
```

If I delete the keycloak (mounted volume) pod first, I can delete it successfully.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]

- secrets-store-csi-driver-provider-aws
- secrets manager

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):v1.4.2
- Kubernetes version: (use `kubectl version`):v1.28.0
