### ISSUE TITLE
Enable customization of securityContext for containers

### ISSUE THREAD

**Issue by andrewmyhre** [kubernetes-sigs/secrets-store-csi-driver#1675]
**Describe the solution you'd like**
The webhook containers currently require privilege escalation to execute. In our organization Kubernetes clusters strictly enforce security context to disallow privilege escalation without sufficient justification. We have been maintaining our own fork of this Helm chart with the following amendment to the upgrade webhook job manifests:

```
spec:
  template:
    spec:
        containers:
        - name: crds-upgrade # same for crds-keep
          securityContext:
            allowPrivilegeEscalation: false
```

The webhooks are able to operate without privilege escalation enabled. We don't want to maintain our own fork of the Helm chart, we would prefer that the securityContext for these containers is able to be configured via the values.yaml file.

**Anything else you would like to add:**

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): `v1.4.6`
- Kubernetes version: (use `kubectl version`):
