### ISSUE TITLE
Cannot Run on Windows Server {2019,2022}

### ISSUE THREAD

**Issue by saedx1** [kubernetes-sigs/secrets-store-csi-driver#1719]
**What steps did you take and what happened:**
`secrets-store` container gives the following error on windows server 2019 & windows server 2022 nodes:
```
I1231 14:58:42.119700    4164 exporter.go:35] "initializing metrics backend" backend="prometheus"
E1231 14:59:03.928704    4164 main.go:167] "failed to start manager" err="could not create RESTMapper from config"
E1231 14:59:03.928704    4164 main.go:85] "unrecoverable error encountered" err="could not create RESTMapper from config"
```

**What did you expect to happen:**
I expected it to just work, and if not to give me a little bit more information about the failure.

**Anything else you would like to add:**

**Which provider are you using:**
I have not gotten to a point where I would setup any of the providers

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): `v1.4.7`
- Kubernetes version: (use `kubectl version`): `1.30`
- Chart Version: 1.4.7
- Yaml Values File:
```

linux:
  enabled: true
  priorityClassName: system-node-critical

windows:
  enabled: true
  priorityClassName: system-node-critical

## Install Default RBAC roles and bindings
rbac:
  install: true

## Install RBAC roles and bindings required for K8S Secrets syncing if true
syncSecret:
  enabled: true

## Enable secret rotation feature [alpha]
enableSecretRotation: true

## Secret rotation poll interval duration
rotationPollInterval: 3600s
```
