### ISSUE TITLE
exposing secret as envvar seems to require the volume to be mounted?

### ISSUE THREAD

**Issue by flixman** [kubernetes-sigs/secrets-store-csi-driver#1832]
**What steps did you take and what happened:**
I am setting  a secret provider class like the following, the goal is exposing the secret aks-agent-registration-pat through an envvar

```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: $SECRETS_PROVIDER_ID
    keyvaultName: $KEYVAULT_NAME
    cloudName: ""
    objects: |
      array:
        - |
          objectName: "aks-agent-registration-pat"
          objectType: secret
          objectVersion: ""
    tenantId: $TENANT_ID
  secretObjects:
    - secretName: azure-keyvault
      type: Opaque
      data:
      - objectName: aks-agent-registration-pat
        key: aks-agent-registration-pat
```

Then I am using the followin pod to test it
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox-debug
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
    - name: secrets-store-inline
      mountPath: /mnt/secrets
      readOnly: true
    env:
      - name: AZP_TOKEN
        valueFrom:
          secretKeyRef:
            name: azure-keyvault
            key: aks-agent-registration-pat
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "azure-keyvault"
  restartPolicy: Never
```
I am only interested in the envvar, and I'd prefer not having all the secrets mounted in /mnt/secrets. This works as is, but if I remove the entry in volumeMounts then the azure-keyvault secret does not get mounted. Is this behavior expected, or am I doing something wrong?

**What did you expect to happen:**
The env var is set with the secret wether the secrets volume is mounted or not.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
Azure Keyvault

**Environment:**
- Secrets Store CSI Driver version: (use the image tag): 1.4.8
- Kubernetes version: (use `kubectl version`):
```
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.31.7
```
