### ISSUE TITLE
[CreateContainerConfigError secret not found] sync secrets option

### ISSUE THREAD

**Issue by mo-saeed** [kubernetes-sigs/secrets-store-csi-driver#236]
**What steps did you take and what happened:**
secret class
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kv-test-env-vars
  namespace: kube-infrastructure
spec:
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - data:
    - key: password                           # data field to populate
      objectName: $SECRET_NAME                # name of the mounted content to sync. this could be the object name or the object alias
    secretName: $SECRET_NAME                  # name of the Kubernetes Secret object
    type: Opaque                              # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls
  provider: azure
  parameters:
    usePodIdentity: "true"             # [OPTIONAL] if not provided, will default to "false"
    keyvaultName:  $KEYVAULT_NAME      # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: $SECRET_NAME
          objectType: secret           # object types: secret, key or cert
          objectVersion: ""            # [OPTIONAL] object versions, default to latest if empty
    resourceGroup: $RESOURCE_GROUP     # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: $SUBSCRIPTION_ID   # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: $TENANT_ID               # the tenant ID of the KeyVault  
```
pod definition
```
kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets-store-env-var
  namespace: kube-infrastructure
  labels:
    aadpodidbinding: $IDENTITY_NAME
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
      env:
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: $SECRET_NAME
            key: password
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kv-test-env-vars"
```

when trying to create the pod, the pod is stuck in `CreateContainerConfigError` state due to the first failure of secret volume mount and secret is not found.

Here's the log 
```
  Warning  FailedMount  2m42s                kubelet, aks-default-28105498-vmss000001  MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Normal   Pulling      76s (x8 over 2m40s)  kubelet, aks-vmss000001  Pulling image "nginx"
  Normal   Pulled       75s (x8 over 2m39s)  kubelet, aks-vmss000001  Successfully pulled image "nginx"
  Warning  Failed       75s (x8 over 2m39s)  kubelet, aks-vmss000001  Error: secret "test-aks-kv-int" not found
``` 
Need to find a way to get the pod ignoring `secret not found` issue till the mount is successfully done, not sure how !

**What did you expect to happen:**
The pod should be up and running with the secret exposed as ENV variable.

**Which provider are you using:**
Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: 0.0.7
- Kubernetes version: 1.16.9

**Comment by aramase** [comment]
@mo-saeed Are you using driver version `v0.0.7`? How did you install the driver and the Azure Key Vault Provider? Could you provide the images for the driver and key vault provider daemon sets? Could you provide the logs from the driver pod? 

>   Warning  FailedMount  2m42s                kubelet, aks-default-28105498-vmss000001  MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded

Could be an issue with fetching the token for identity using `aad-pod-identity`. We can get more info from the logs.

**Comment by mo-saeed** [comment]
Hi @aramase 
- sorry version for azure-provider is 0.0.6, the helm chart version is 0.0.7 and csi-driver version is 0.0.11
- using helm chart 
- no it's not an issue with aad-pod-identity coz it works without the part of env variable
```
      env:
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: $SECRET_NAME
            key: password
```
as i explained the mount is not successful from the first time, so after the first time the pod stuck in config error due to missing secret.

- that's the log 
```
Warning FailedMount 2m42s kubelet, aks-default-28105498-vmss000001 MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
and after it the pod is stuck in the config error status due to the missing secret so no more logs.
