### ISSUE TITLE
Sync of k8 secrets not happening

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [kubernetes-sigs/secrets-store-csi-driver#290]
**What steps did you take and what happened:**
I have set up a SecretProviderClass that connects to my Azure Key Vault which works correctly as I can mount the volume and get the secrets out (as seen in the tutorial). I have added secretObjects to sync with th k8 secrets but the secret is not appearing. 
I'm trying to create a simple Opaque secret. Is the secret not created if it does not exist?

**What did you expect to happen:**
That a secret would be created and and synced.

**Which provider are you using:**
I'm using Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): us.gcr.io/k8s-artifacts-prod/csi-secrets-store/driver:v0.0.12
- Kubernetes version: (use `kubectl version`): v1.17.7

**Comment by thomasfrederikhoeck** [comment]
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kv-aa
spec:
  provider: azure                   
  parameters:
    useVMManagedIdentity: "true"   
    userAssignedIdentityID: my_vmss_id
    keyvaultName: my_kw_name
    resourceGroup: my_rscg
    subscriptionId: my_sub
    tenantId: mytenantID
    objects:  |
      array:
        - |
          objectName: 'MY-PW'
          objectType: secret      
        - |
          objectName: 'MY-USER'
          objectType: secret      
  secretObjects:   
  - secretName: kvaa   
    type: Opaque   
    data:
    - objectName: 'MY-PW'      
      key: 'MY_PW'     
    - objectName: 'MY-USER' 
      key: 'MY_USER'    
      
```

**Comment by thomasfrederikhoeck** [comment]
Okay, I realized that I should not expect to see a Secret appear in my secrets, and that I should still mount the volume and then declare the environment variable. I don't think this is complete clear from the user guide. From the user guide it looks like you will get a k8 secret that you can simply access like if you defined it yourself. :-)

**Comment by thomasfrederikhoeck** [comment]
Okay, so the syncing to k8 secrets is happening but very delayed.

**Comment by aramase** [comment]
@thomasfrederikhoeck Thank you for opening the issue 👍 

The reconcile loop in driver periodically syncs every 5 mins. If the `SecretProviderClass` is updated after the initial creation, then the reconcile will pick it up when the `SecretProviderClass` is picked off the queue again. 

> Okay, I realized that I should not expect to see a Secret appear in my secrets, and that I should still mount the volume and then declare the environment variable. I don't think this is complete clear from the user guide. From the user guide it looks like you will get a k8 secret that you can simply access like if you defined it yourself. :-)

Yes, the mounting in the volume is the primary purpose of the driver. The sync k8s feature is an addon that consumes the mounted content to reflect as k8s secret. 

```
In some cases, you may want to create a Kubernetes Secret to mirror the mounted content. Use the optional secretObjects field to define the desired state of the synced Kubernetes secret objects
```

We'll update the doc to mention the mount is mandatory and sync k8s secret requires the mount.

**Comment by thomasfrederikhoeck** [comment]
Thank you for the answer @aramase 😄  So just to be clear - if I want to use the option with the environmental variables I need to :

1. Install Secret Store CSI Driver 
2. Create SecretProviderClass with `secretObjects` matcing objects in `objects`
3. Wait for at least 5 minutes
4. In the deployment manaifest of my app mount the volume to the deployment _AND_ add 
```
           
  - name: API_KEY
    valueFrom:
        secretKeyRef:
            name: kvaa
            key: K8-DEMO-APIKEY
```
