### ISSUE TITLE
SecretProviderClass loaded from the wrong namespace

### ISSUE THREAD

**Issue by iMoses** [kubernetes-sigs/secrets-store-csi-driver#304]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Create two namespaces: `dev1` and `dev2`
Upload different `SecretProviderClass` resource to each with the same name, e.g.
```
spec:
  parameters:
    objects: |
      array:
        - |
          objectName: my-awesome-secret
          objectAlias: awesome-secret
          objectType: secret
```
```
spec:
  parameters:
    objects: |
      array:
        - |
          objectName: their-awesome-secret
          objectAlias: awesome-secret
          objectType: secret
```
Mount the secret on each namespace and notice it's always `dev1` being loaded.. that's because alphabetically it's matched before the current namespace.

**What did you expect to happen:**
Each namespace should have used the `SecretProviderClass` resource deployed to it.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I noticed this bug two months ago and the issue I posed on was closed, yet the issue still exist.
https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/223#issuecomment-640272946

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]
Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): helm 0.0.10
- Kubernetes version: (use `kubectl version`): 1.17.9
