### ISSUE TITLE
Getting Permission denied error while mounting a secret from external vault  inside a kubernetes cluster using a Pod deployment

### ISSUE THREAD

**Issue by forumsheth** [kubernetes-sigs/secrets-store-csi-driver#338]
**What steps did you take and what happened:**
I have deployed vault on bosh using the following repo: https://github.com/cloudfoundry-community/vault-boshrelease
I am able to access vault and also able to create secrets.
After that I deployed secret store csi driver inside my kubernetes cluster using the following repo: https://github.com/kubernetes-sigs/secrets-store-csi-driver
Also deployed the vault- provider. Ref : https://github.com/hashicorp/secrets-store-csi-driver-provider-vault
The deployments were successful and the pods were in running state.
Now to mount the secrets on a pod form vault, tried to deploy the sample application: https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/blob/master/examples/nginx-pod-vault-inline-volume-secretproviderclass.yaml
For that created the following in vault:
1. A secret
2. Enabled Kubernetes Authentication
3. Uploaded kubernetes cluster configurations for authentication using the following command:
     vault write auth/kubernetes/config \
        token_reviewer_jwt="$TOKEN_REVIEW_JWT" \
        kubernetes_host="$KUBE_HOST" \
        kubernetes_ca_cert="$KUBE_CA_CERT"
4. Created a policy
![image](https://user-images.githubusercontent.com/29745881/95593958-f1d35400-0a67-11eb-81ee-8e3ffcdd8496.png)
5. Attached it to a role
![image](https://user-images.githubusercontent.com/29745881/95594048-116a7c80-0a68-11eb-8de9-d9d9b9cc2b6e.png)

**What did you expect to happen:**
So ideally the sample pod should get deployed with the given role. But it is giving the following error:
![image](https://user-images.githubusercontent.com/29745881/95594485-a2415800-0a68-11eb-9149-3988e27b03f0.png)
Can any one help me with this? Am I missing anything? I am not able to understand the issue.

**Anything else you would like to add:**
So I tried to do it manually  using the curl command. And I am able to login and with the client token generated also able to fetch the secrets on the path allowed in the policy.
Some screenshots:
Using curl command able to to login and get the client token
![image](https://user-images.githubusercontent.com/29745881/95595332-ab7ef480-0a69-11eb-94ea-8ca68b846a7b.png)
Using the same client token able to see secrets on allowed path only!
![image](https://user-images.githubusercontent.com/29745881/95595544-e7b25500-0a69-11eb-833f-495ef83837ea.png)
Also checked the token capabilities
![image](https://user-images.githubusercontent.com/29745881/95595762-28aa6980-0a6a-11eb-9aaf-b3c15b4a83f9.png)

All seems working manually!

**Which provider are you using:**

HashiCorp Vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v0.0.15
- Kubernetes version: (use `kubectl version`): v1.16.8

**Comment by aramase** [comment]
@tomhjp Could you help take a look at this?

**Comment by tomhjp** [comment]
Hi @forumsheth, it looks to me like the sample application you deployed is not running as the k8s service account that is configured on Vault. A service account called `secrets-store-csi-driver` from the `default` namespace is bound to the `example-role` Vault role. But the sample application uses the `default` service account. If not, could you confirm how you generated the `jwt` that you manually logged in with?

**Comment by forumsheth** [comment]
Hi @tomhjp Even after explicitly providing the service account as secrets-store-csi-driver it is giving the same error.
I generated the jwt using the follwoing command:
kubectl get secret secrets-store-csi-driver-token-8jdq8  -o go-template='{{ .data.token }}' | base64 --decode
And then updated it in vault:
vault write auth/kubernetes/config \
        token_reviewer_jwt="<jwt-token>" \
        kubernetes_host="$KUBE_HOST" \
        kubernetes_ca_cert="$KUBE_CA_CERT"
And then using the curl command: curl --request POST --data '{"jwt": "<token>", "role": "example-role"}' https://<vault-ip>:8200/v1/auth/kubernetes/login -k -s
I am able to login and fetch the generated client token.

**Comment by forumsheth** [comment]
Can anyone please give me an update on this? @tomhjp @aramase

**Comment by aramase** [comment]
ping @tomhjp

**Comment by forumsheth** [comment]
Hi @tomhjp can you help me with this issue?

**Comment by tomhjp** [comment]
Sorry for the delay. It's hard to say what could be going wrong without the ability to locally reproduce. One thing worth noting is that if you try to read a Vault secret path that does not exist, you will get a permission denied error to ensure enumeration attacks don't leak information. With that in mind, I wonder if the secret provider class you have deployed is misconfigured to read the wrong secret path? If you have used the [example](https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/blob/master/examples/nginx-pod-vault-inline-volume-secretproviderclass.yaml) you mentioned without modification, then it's the secret provider class named "vault-foo".

If this doesn't help, perhaps you could provide a full set of yaml configs for me, or generally a reliable way to produce your environment in a local kind cluster? There are a lot of moving parts, so it's really tricky to diagnose the issue without being to inspect all the config. If some parts were installed by helm, just the command line you used to install and the tag selected are fine instead of the yaml, but I would at least need to look at the driver, provider, app (nginx in this case) and secret provider class configs.

**Comment by forumsheth** [comment]
Hi @tomhjp , yeah I am aware that it gives a permission denied on a wrong path. As you can see in the above screenshots attached the capabilities show that only the path that has permission shows : create,delete,list,read  and other path shows deny.

I have changed the secret path in my example and accordingly configured the secretproviderclass.
The yaml files used are as below:
**Driver:** 
1. In the rbac-secretproviderclass.yaml file added the below ClusterRoleBinding
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: secrets-store-csi-driver
    namespace: default
```
2. In the secrets-store-csi-driver.yaml file changed the path from **var/lib** to  **var/vcap/data** 
Rest all the files are same as given in the repo : https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/deploy

**Vault-provider:**
Uisng the same file as given here : https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/blob/master/deployment/provider-vault-installer.yaml

**Sample app:**
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-grafana
spec:
  provider: vault
  parameters:
    roleName: "example-role"
    vaultAddress: "https://x.x.x.x:8200"
    vaultSkipTLSVerify: "true"
    objects:  |
      array:
        - |
          objectPath: "/grafana-pwd"
          objectName: "GF_SECURITY_ADMIN_PASSWORD"
          objectVersion: ""
```
```
kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets-store-inline
spec:
  serviceAccountName: secrets-store-csi-driver
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "vault-grafana"

```
