### ISSUE TITLE
Mount volume setup failed error is coming

### ISSUE THREAD

**Issue by smartaquarius10** [kubernetes-sigs/secrets-store-csi-driver#343]
Team,

I have used aad-pod-identity to establish connection between Azure Key vault and csi driver. I'm trying to pull 3 secrets from kv using 2 **secredproviderclasses** but getting this error. Can you help me please?

```
MountVolume.SetUp failed for volume "secrets-store-inline-cert" : kubernetes.io/csi: mounter.SetupAt failed: 
rpc error: code = Unknown desc = failed to mount secrets store objects for pod kube-system/nginx-ingress-controller-6ff4995998-mfqdb,
err: rpc error: code = Unknown desc = failed to mount objects, 
error: failed to get objectType:secret, objectName:, objectVersion:: keyvault.BaseClient#GetSecret: Failure responding 
to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal 
array into Go struct field SecretBundle.value of type string' JSON = '{
  "value": [
    {
      "id": "https://xxxxxxx.vault.azure.net/secrets/tlscert",
      "attributes": {
        "enabled": true,
        "created": 1602345162,
        "updated": 1602345162,
        "recoveryLevel": "Recoverable+Purgeable"
      },
      "tags": {
        "file-encoding": "utf-8"
      }
    },
    {
      "id": "https://xxxxxx.vault.azure.net/secrets/tlskey",
      "attributes": {
        "enabled": true,
        "created": 1602345795,
        "updated": 1602345795,
        "recoveryLevel": "Recoverable+Purgeable"
      },
      "tags": {
        "file-encoding": "utf-8"
      }
    },
    {
      "id": "https://xxxxxx.vault.azure.net/secrets/X-Header-license",
      "attributes": {
        "enabled": true,
        "created": 1602345917,
        "updated": 1602345917,
        "recoveryLevel": "Recoverable+Purgeable"
      },
      "tags": {
        "file-encoding": "utf-8"
      }
    }
  ],
  "nextLink": null
}
'
```

```
MountVolume.SetUp failed for volume "secrets-store-inline-jwt" : kubernetes.io/csi: mounter.SetupAt failed: 
rpc error: code = Unknown desc = failed to mount secrets store objects for pod kube-system/nginx-ingress-controller-6ff4995998-mfqdb, err: rpc error: code = Unknown desc = failed to mount objects, 
error: failed to get objectType:secret, objectName:, objectVersion:: keyvault.BaseClient#GetSecret: Failure
 responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal array 
into Go struct field SecretBundle.value of type string' JSON = 
{
  "value": [
    {
      "id": "https://xxxxxx.vault.azure.net/secrets/tlscert",
      "attributes": {
        "enabled": true,
        "created": 1602345162,
        "updated": 1602345162,
        "recoveryLevel": "Recoverable+Purgeable"
      },
      "tags": {
        "file-encoding": "utf-8"
      }
    },
    {
      "id": "https://xxxxxxx.vault.azure.net/secrets/tlskey",
      "attributes": {
        "enabled": true,
        "created": 1602345795,
        "updated": 1602345795,
        "recoveryLevel": "Recoverable+Purgeable"
      },
      "tags": {
        "file-encoding": "utf-8"
      }
    },
    {
      "id": "https://xxxxxxx.vault.azure.net/secrets/X-Header-license",
      "attributes": {
        "enabled": true,
        "created": 1602345917,
        "updated": 1602345917,
        "recoveryLevel": "Recoverable+Purgeable"
      },
      "tags": {
        "file-encoding": "utf-8"
      }
    }
  ],
  "nextLink": null
}
```

**SecretProviderClass 1**:- 
```
kind: SecretProviderClass
metadata:
  name: azure-kv-tls
spec:
  provider: azure
  secretObjects:                                
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data:
    - objectName: tlscert
      key: tls.key
    - objectName: tlskey
      key: tls.crt
  parameters:
    usePodIdentity: "true"
    keyvaultName: "xxxxxxx"                        # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: tlscert
          objectType: secret
        - |
          objectNAme: tlskey
          objectType: secret
    tenantId: "xxxxxxxxxxxxxxxxxxxxxxxxxxx"             # set default directory GUID
```
**SecretProviderClass 2:-**
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kv-jwt
spec:
  provider: azure
  secretObjects:                                
  - secretName: ingress-jwt-csi
    type: Opaque
    data:
    - objectName: X-Header-license
      key: X-Header-license
  parameters:
    usePodIdentity: "true"
    keyvaultName: "mykeyvault-dev"                        # the name of the KeyVault
    objects: |
      array:
        - |
          objectNAme: X-Header-license
          objectType: secret
    tenantId: "xxxxxxxxxxxxxxxxxxxxxxxxxxx"             # set default directory GUID
```
Here 3 different secrets saved in key vault are tlscert, tlskey and X-Header-license and my nginx deployment.yaml is 

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-ingress-controller
  namespace: kube-system
  labels:
    aadpodidbinding: app
    app: nginx-ingress
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: Helm
    chart: nginx-ingress-1.41.3
    heritage: Helm
    release: nginx-ingress
  annotations:
    deployment.kubernetes.io/revision: '6'
    meta.helm.sh/release-name: nginx-ingress
    meta.helm.sh/release-namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
      release: nginx-ingress
  template:
    metadata:
      creationTimestamp: null
      labels:
        aadpodidbinding: app
        app: nginx-ingress
        app.kubernetes.io/component: controller
        component: controller
        release: nginx-ingress
    spec:
      volumes:
        - name: secrets-store-inline-cert
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kv-tls
        - name: secrets-store-inline-jwt
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kv-jwt
      containers:
        - name: nginx-ingress-controller
          image: 'us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1'
          args:
            - /nginx-ingress-controller
            - >-
              --default-backend-service=kube-system/nginx-ingress-default-backend
            - '--election-id=ingress-controller-leader'
            - '--ingress-class=nginx'
            - '--configmap=kube-system/nginx-ingress-controller'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP        
          volumeMounts:
            - name: secrets-store-inline-cert
              readOnly: true
              mountPath: /mnt/secrets-store-cert
            - name: secrets-store-inline-jwt
              readOnly: true
              mountPath: /mnt/secrets-store-jwt
```
  ...................
**AAD-Pod-identity helm template is:-** 
```
mic:
  nodeSelector:
    pool: xxx
metadata:
  namespace: utils
azureIdentities:
- name: "app-identity" 
  namespace: default
  type: 0
  resourceID: ${resourceID}
  clientID: ${clientID}
  binding:
    name: "app-identity-binding"
    selector: "app"

```
