### ISSUE TITLE
Possibility to annotate the created secret with CSI driver

### ISSUE THREAD

**Issue by aramase** [kubernetes-sigs/secrets-store-csi-driver#356]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Original issue - https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/279

At the moment the secrets can only be used within the namespace that the pod mounts the disk and secret is created. Using kubed we could share that secret with other namespaces. This will allow us to have single namespace with some alpine pod running all the mounts with secret and spread the secrets across namespaces.

For this to work the secret has to be annotated. At the moment it is not possible to annotate on creation/before. And every time you update the secret and redeploy mounts the manual annotation is removed.

I guess possibility of adding annotation to the secret on secreptorvider level would be enough.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):

**Comment by sbose78** [comment]
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: my-provider
spec:
  provider: vault                             # accepted provider options: azure or vault or gcp
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - data:
    - metadata:
         labels:
           environment: production
           app: nginx
      key: username                           # data field to populate
      objectName: foo1                        # name of the mounted content to sync. this could be the object name or the object alias
    secretName: foosecret                     # name of the Kubernetes Secret object
    type: Opaque 
```
Hi!
Is this how you would expect it to be specified?
