### ISSUE TITLE
Secret versions not updating on Pod Restart

### ISSUE THREAD

**Issue by jamesikanos** [kubernetes-sigs/secrets-store-csi-driver#372]
I have created an NGINX pod and am injecting secrets via both the filesystem (mount) and environment variables.

When the pod boots, the secrets are all present and correct.

Then, I add a new version to my Azure secret.

- If I delete the pod and re-create, the secrets are updated to the latest version
- If I restart the pod (using `nginx -s stop` inside the pod) then the previous version remains

The documentation implies that restarting a pod will fetch the latest version of the secrets. How can this be achieved?

Steps to Reproduce:

- Attach a secret
- Boot a static pod (no deployment)
- Update the secret
- Force Restart the pod internally (fake a 'crash')
- Observe that pod uses old secret

Please advise.

**Comment by jamesikanos** [comment]
Follow up, I gather that this is a "known-issue" (https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.limitations.md#mounted-content-and-kubernetes-secret-not-updated-after-secret-is-updated-in-external-secrets-store).

In this case, can the ReadMe.md be updated to remove "and restart" from the documentation?

**Comment by aramase** [comment]
> If I restart the pod (using nginx -s stop inside the pod) then the previous version remains

@jamesikanos Restarting the container process doesn't create a new pod sandbox. The CSI driver is only invoked by the kubelet as part of pod creation volume mount. We've added support for auto rotation alpha feature that periodically fetches the latest content from external secrets store and updates the volume mount and Kubernetes secret. Here are some doc links for this - 

- https://github.com/kubernetes-sigs/secrets-store-csi-driver#optional-enable-auto-rotation-of-secrets
- https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/docs/README.rotation.md

**Comment by aramase** [comment]
@jamesikanos Did you get a chance to try out the auto rotation feature?

**Comment by jamesikanos** [comment]
Hi @aramase. Apologies for the delay.

I haven't tried it yet, but I certainly will shortly.

Thank you for your response.

**Comment by Dyllaann** [comment]
Hi @aramase, I'll comment on this issue as I wanted to re-open #321, but it seems this issue is similar.
I think the auto-rotation feature fixes the problem where secrets are changed from the vault, but not when secrets are changed in the SecretProviderClass.

Assume scenario 1 where an application with the following snippets are deployed:
SecretProviderClass.yaml (partial)
```yaml
secretObjects:
  - data:
    - key: mysecret1
      objectName: mysecret1
    secretName: secret-object
    type: Opaque
```
Pod.yaml (Partial)
```yaml
env:
- name: MYSECRET1_ENV_VAR
  valueFrom:
    secretKeyRef:
      name: secret-object
      key: mysecret1
```

The pod boots up, mounts the volume, the secret is created and the environment variable is linked from the secret.
Now, we add a second secret into the SecretProviderClass
```yaml
secretObjects:
  - data:
    - key: mysecret1
      objectName: mysecret1
    - key: mysecret2
      objectName: mysecret2
    secretName:secret-object
    type: Opaque
```
and mount it in the pod similarly to the first secret like
```yaml
env:
- name: MYSECRET1_ENV_VAR
  valueFrom:
    secretKeyRef:
      name: secret-object
      key: mysecret1
- name: MYSECRET2_ENV_VAR
  valueFrom:
    secretKeyRef:
      name: secret-object
      key: mysecret2
```
and update the deployment.

Now, the pod will be refreshed because it's spec changed.
The result of this is:
1. The pod will boot up and mount the CSI volume
2. The secrets are **both** correctly mounted under `/mnt/secrets-store/mysecret1` and `/mnt/secrets-store/mysecret2`
3. The secret **object** `secret-object` is not renewed, thus still only having `mysecret1`
4. The environment variable mount for `MYSECRET2_ENV_VAR` fails, because `mysecret2` is not in the object.

The problem with this is that I don't need the reconciler feature itself. My secrets that need to be pulled from KeyVault are not updated periodically. I just need to chance **which** secrets are mounted to each pod.
If I were to enable the reconciler, there is still the problem where my pod will be error looping untill the reconciler renewed the secret object. Besides that, I don't see the use case of enabling the reconciler with a refresh interval of 10 seconds. On the other hand, setting it to an hour could mean my pod doesn't start up for 59 minutes because it is unable to reference the `secretKeyRef`

I hope this post explains the scenario correctly! Let me know if certain things are still unclear :)
