### ISSUE TITLE
How do I use this in a deployment yaml file ?

### ISSUE THREAD

**Issue by kanukhosla** [kubernetes-sigs/secrets-store-csi-driver#379]
I created this yaml based on your tutorial but got an error while deploying this file using HELM. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kk-test3
spec:
  replicas: 1
  selector:
      matchLabels:
        app: kk-test3
  template:
    metadata:
      labels:
        app: kk-test3
    spec:
      containers:
      - name: kk-test3
        image: nginx
        volumeMounts:
        - name: azurefilesharetest3
          mountPath: /usr/share/nginx/html
      volumes:
      - name: azurefilesharetest3
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "test3spc"
          nodePublishSecretRef:
            name: secrets-store-creds-test3
        azureFile:
          shareName: kk-test3-fileshare
          secretName: kktest3storage
          readOnly: false

```

I get this error while deploying :

`Error: UPGRADE FAILED: failed to create resource: Deployment.apps "kktest3" is invalid: [spec.template.spec.volumes[0].csi: Forbidden: may not specify more than 1 volume type, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "azurefilesharetest3"]`

**Comment by aramase** [comment]
@kanukhosla As the error suggests, you can't use multiple volume sources for a single volume. You would need to create a volume for each source. 

Here is a sample deployment for using the CSI volume - https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/azure/nginx-deployment-synck8s-azure.yaml.

**Comment by kanukhosla** [comment]
@aramase could you help me rewrite my yaml file ? I found no difference in my yaml file except for the block:
````
azureFile:
          shareName: kk-test3-fileshare
          secretName: kktest3storage
          readOnly: false
````
