### ISSUE TITLE
Secret object not renewed on change in SecretProviderClass

### ISSUE THREAD

**Issue by Dyllaann** [kubernetes-sigs/secrets-store-csi-driver#389]
Hi!
I found the following issue, which I also listed in #321, but I think it's not explained properly. I'll try to describe it using a scenario below.

**What steps did you take and what happened:**
Assume scenario 1 where an application with the following snippets are deployed:
SecretProviderClass.yaml (partial)
```yaml
secretObjects:
  - data:
    - key: mysecret1
      objectName: mysecret1
    secretName: secret-object
    type: Opaque
```
Deployment.yaml (Partial)
```yaml
env:
- name: MYSECRET1_ENV_VAR
  valueFrom:
    secretKeyRef:
      name: secret-object
      key: mysecret1
```

The pod boots up, mounts the volume, the secret is created and the environment variable is linked from the secret.
Now, we add a second secret into the SecretProviderClass
```yaml
secretObjects:
  - data:
    - key: mysecret1
      objectName: mysecret1
    - key: mysecret2
      objectName: mysecret2
    secretName:secret-object
    type: Opaque
```
and mount it in the pod similarly to the first secret like
```yaml
env:
- name: MYSECRET1_ENV_VAR
  valueFrom:
    secretKeyRef:
      name: secret-object
      key: mysecret1
- name: MYSECRET2_ENV_VAR
  valueFrom:
    secretKeyRef:
      name: secret-object
      key: mysecret2
```
and update the deployment.

Now, the pod will be refreshed because it's spec changed.
The result of this is:
1. The pod will boot up and mount the CSI volume
2. The secrets are **both** correctly mounted under `/mnt/secrets-store/mysecret1` and `/mnt/secrets-store/mysecret2`
3. The secret **object** `secret-object` is not renewed, thus still only having `mysecret1`
4. The environment variable mount for `MYSECRET2_ENV_VAR` fails, because `mysecret2` is not in the object.

**What did you expect to happen:**
I expected the secret to change. After the deployment update, the pod restarted and I expected the secret object `secret-object` to contain keys `mysecret1` and `mysecret2`

**Anything else you would like to add:**
The problem with this is that I don't need the reconciler feature itself. My secrets that need to be pulled from KeyVault are not updated periodically. I just need to chance **which** secrets are mounted to each pod.
If I were to enable the reconciler, there is still the problem where my pod will be error looping untill the reconciler renewed the secret object. Besides that, I don't see the use case of enabling the reconciler with a refresh interval of 10 seconds. On the other hand, setting it to an hour could mean my pod doesn't start up for 59 minutes because it is unable to reference the `secretKeyRef`

**Which provider are you using:**
Azure Key Vault

**Environment:**
- Secrets Store CSI Driver version: (use the image tag): 0.0.16
- Kubernetes version: (use `kubectl version`): 1.16.15
