### ISSUE TITLE
Auto rotation of mounted contents and synced Kubernetes Secrets enabled but latest version not synced

### ISSUE THREAD

**Issue by uthsab** [kubernetes-sigs/secrets-store-csi-driver#390]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- installed secret-store-provider-azure using helm and setting enableSecretRotation=True
- created secretProviderClass to sync secret from given AKV and sync it to given k8s secret
- created dummy pod and mounted the above secret on it. 
- created new version of secret and checked value after 5 minutes

**What did you expect to happen:**
The new version should have been used. (Default poll interval is 2 minutes. Waited for 5 minutes instead)
This did not happen. It keeps referring to the same version, until the pod is recreated. 

Have provided the detailed steps below. Let me know if I am missing something. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Command history - 
```
uthsa@Azure:~$ helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --set enableSecretRotation=True --generate-nameNAME: csi-secrets-store-provider-azure-1605706458
LAST DEPLOYED: Wed Nov 18 13:34:24 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
uthsa@Azure:~$ kubectl apply -f spc.yaml
secretproviderclass.secrets-store.csi.x-k8s.io/azure-sync created
uthsa@Azure:~$ kubectl get secret | grep foosecret
uthsa@Azure:~$ kubectl apply -f dummy.yaml
pod/dummy-1 created
uthsa@Azure:~$ kubectl get secret | grep foosecret
foosecret                                                           Opaque                                1      5s
uthsa@Azure:~$ date
Wed Nov 18 13:36:26 UTC 2020
uthsa@Azure:~$ kubectl get secretproviderclasspodstatus dummy-1-default-azure-sync -o yaml | grep -i version
...
    version: e20c3e1b4bb64727bc1edd8459334921
uthsa@Azure:~$ echo "created new version"
created new version
uthsa@Azure:~$ date
Wed Nov 18 13:38:04 UTC 2020
uthsa@Azure:~$ date
Wed Nov 18 13:44:00 UTC 2020
uthsa@Azure:~$ kubectl get secretproviderclasspodstatus dummy-1-default-azure-sync -o yaml | grep -i version
...
    version: e20c3e1b4bb64727bc1edd8459334921
uthsa@Azure:~$
```

spc.yaml

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure
  secretObjects:                                 # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: foosecret
    type: Opaque
    labels:                                   
      environment: "test"
    data: 
    - objectName: secretalias                    # name of the mounted content to sync. this could be the object name or object alias 
      key: username
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "28496b9f-7723-4f08-b325-7b4d45d8b826"                 
    keyvaultName: "utb-kv"               # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: "test-sec-2"
          objectType: secret                     # object types: secret, key or cert
          objectAlias: secretalias
          objectVersion: ""
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47" # the tenant ID of the KeyVault

```
dummy.yaml

```
apiVersion: v1
kind: Pod
metadata:
  name: dummy-1
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "azure-sync"
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  hostNetwork: true
  dnsPolicy: Default

```

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]
Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):0.017
- Kubernetes version: (use `kubectl version`): 1.18.8
