### ISSUE TITLE
Add podname and/or podIP label to metrics.

### ISSUE THREAD

**Issue by mitsutaka** [kubernetes-sigs/secrets-store-csi-driver#407]
**Describe the solution you'd like**
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/v0.0.18/docs/README.metrics.md

By default, csi-driver uses ports `:8095` and `:8888` to provide metrics endpoints.
Some SCI specific metrics have already been implemented.
I want to add a podname and/or podIP label to identify which pod's metrics prometheus scraped

**Anything else you would like to add:**
I started to run secrets-store-csi-driver on the many nodes. `instance` label might be help to recognize secrets-store-csi-driver pod.

```
total_node_publish_error{instance="10.xx.xx.xx:8888",error_type="FailedToMount",os_type="linux",provider="vault"} 4
```

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v0.0.18
- Kubernetes version: (use `kubectl version`): v1.16

**Comment by mitsutaka** [comment]
If we leave it to prometheus by relabel_config, we can guide it in the doc and close it.

**Comment by ZhijunZhao** [comment]
@mitsutaka Do you have a working solution? If yes, could you share a sample scrape config? 

Most projects use service to expose an HTTP endpoint for prometheus to scrap. This project simply exposes a port. I'm not sure how to instruct prometheus to scrap the ports of all kubernetes nodes.

**Comment by mitsutaka** [comment]
@ZhijunZhao I haven't tried scraping yet, but I suppose it can be done by typical scraping configuration with service discovery.

This is example of annotation for Prometheus service discovery
```
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8095"
```

And this is sample scrape config.

```
  - job_name: "secrets-store-csi-driver"
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ["<namespace for secrets-store-csi-driver>"]
    relabel_configs:
      - source_labels: [__address__] # __address__="xx.xx.xx.xx:yyyy" -> instance="xx.xx.xx.xx"
        action: replace
        regex: ([^:]+)(?::\d+)?
        replacement: ${1}
        target_label: instance
```

Upstream's helm chart still enables `hostNetwork: true`( and it is planned #349 ) but I confirmed csi-driver DaemonSet works without hostNetwork. In my case, `__address__` is PodIP.

Alternatively, we can use `__meta_kubernetes_pod_ip` as source_labels and then relabel to the `instance`
Reference: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#pod

**Comment by ZhijunZhao** [comment]
@mitsutaka Thanks for the help! Looks like simply adding the annotations is sufficient, because the default scrape config includes below settings. 

```
- job_name: kubernetes-pods
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
    ...
```

The helm chart doesn't provide the parameter to add pod annotations. I'll open an issue for it.
