### ISSUE TITLE
The helm chart doesn't provide parameter for adding pod annotations

### ISSUE THREAD

**Issue by ZhijunZhao** [kubernetes-sigs/secrets-store-csi-driver#408]
**What steps did you take and what happened:**

I'm trying to setup Prometheus to scrap metrics from the driver. It looks like adding below annotations to the pods is the optimal solution. With below annotation, Prometheus can scrap the pods via service discovery. 

```
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'

```

**What did you expect to happen:**

The helm chart should provide a parameter for adding annotations to the driver pods. Please advise if there are alternative solutions. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which provider are you using:**
Azure Key Vault provider.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v0.0.18
- Kubernetes version: (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"c86ad89b8715ed17fd55b87cbb2888ccc6fa9878", GitTreeState:"clean", BuildDate:"2020-09-25T01:53:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ZhijunZhao** [comment]
@aramase Your PR supports **daemonset** annotation, instead of **pod** annotations.  

To let Prometheus discover the driver pods, annotations has to be added 

```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  annotations:
    _NOT-HERE_
spec:
  selector:
    matchLabels:
      app: secrets-store-csi-driver
  template:
    metadata:
      annotations:
        _HERE_
```
