### ISSUE TITLE
Problems with log configurations 

### ISSUE THREAD

**Issue by pierluigilenoci** [kubernetes-sigs/secrets-store-csi-driver#442]
**What steps did you take and what happened:**

* We have configured the log to be in JSON format but we lose some information 
* We have configured the pod to generate logs at verbosity 1 (WARNING) but still log type 0 (INFO)

* We want to have the JSON format and verbosity level for all pod containers but some configurations are missing in the Helm Chart.

**What did you expect to happen:**

* The logs have the same information regardless of the format 
* No more logs are generated for level 0 (INFO) if the level is 1 (WARNING) 
* JSON format also for `node-driver-registrar` and `liveness-probe`
* Verbosity level for `node-driver-registrar`

**Anything else you would like to add:**

Chart configuration:
```yaml
logLevel:
  debug: false
logVerbosity: 1
logFormatJSON: true
livenessProbe:
  logLevel: 1
enableSecretRotation: true
rotationPollInterval: 2m
```

Log with verbosity 1 (WARNING) in text format 
```text
I0205 10:07:14.524904       1 secretproviderclasspodstatus_controller.go:183] "reconcile started" spcps="[redacted namespace]/[redacted secret provider]"
I0205 10:07:14.524921       1 secretproviderclasspodstatus_controller.go:183] "reconcile started" spcps="[redacted namespace]/[redacted secret provider]"
I0205 10:07:14.524938       1 secretproviderclasspodstatus_controller.go:183] "reconcile started" spcps="[redacted namespace]/[redacted secret provider]"
```

Log with verbosity 1 (WARNING) in JSON format
```json
{"ts":1612518712649.7717,"msg":"reconcile started","v":0}
{"ts":1612518712649.785,"msg":"reconcile started","v":0}
{"ts":1612518724148.2576,"msg":"reconcile started","v":0}
{"ts":1612518724148.306,"msg":"reconcile complete","v":0}
{"ts":1612518910965.3506,"msg":"reconcile started","v":0}
{"ts":1612518924913.5608,"msg":"reconcile started","v":0}
```

`spcps` is missing, `secretproviderclasspodstatus_controller.go:183` is missing, `verbosity` is `0`.

Ref: https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/387

**Which provider are you using:**

Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: `v0.0.19`
- Kubernetes version: `Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"c86ad89b8715ed17fd55b87cbb2888ccc6fa9878", GitTreeState:"clean", BuildDate:"2020-09-25T01:53:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by pierluigilenoci** [comment]
@aramase could you please take a look?

**Comment by pierluigilenoci** [comment]
I also tried to set level 2 (ERROR):

Chart configuration:
```yaml
logVerbosity: 2
logFormatJSON: true
secrets-store-csi-driver:
  logLevel:
    debug: false
  logVerbosity: 2
  logFormatJSON: true
  livenessProbe:
    logLevel: 2
  enableSecretRotation: true
  rotationPollInterval: 2m
```

`secret-store` logs with verbosity 2 (ERROR) in JSON format
```json
{"ts":1612524619149.1863,"msg":"reconcile started","v":0}
{"ts":1612524619149.2927,"msg":"reconcile complete","v":0}
{"ts":1612524619149.6929,"msg":"reconcile started","v":0}
{"ts":1612524619149.8096,"msg":"reconcile complete","v":0}
```

`liveness-probe` logs with verbosity 2 (ERROR) in text format
```text
I0205 11:32:56.717662       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0205 11:33:11.717745       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0205 11:33:26.717765       1 connection.go:153] Connecting to unix:///csi/csi.sock
I0205 11:33:41.717788       1 connection.go:153] Connecting to unix:///csi/csi.sock
```
