### ISSUE TITLE
Add pod security policy to the helm chart

### ISSUE THREAD

**Issue by mo-saeed** [kubernetes-sigs/secrets-store-csi-driver#450]
**Describe the request**
Right now we have a pod security policy enabled in our k8s clusters that prevent the creation of certain volumes and allow only certain capabilities, etc.. this is a blocker to deploy secrets-store-csi-driver properly so we had to create the following pod security policy manually.

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: secrets-store
spec:
  seLinux:
    rule: RunAsAny
  privileged: true
  volumes:
    - hostPath
    - secret
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp-secrets-store-role
  namespace: NAME
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - secrets-store
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-secrets-store-role-binding
  namespace: NAME
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp-secrets-store-role
subjects:
- kind: ServiceAccount
  name: secrets-store-csi-driver
  namespace: NAME
```

**Explain why AAD Pod Identity needs it**
To deploy secrets-store-csi-driver successfully in k8s cluster with a restricted pod-security policy enabled.

**Describe the solution you'd like**
Merge the pod security policy mentioned above in the software helm chart, and keep it updated with the new software releases.

**Describe alternatives you've considered**
the other alternative is to create the pod security policy manually, which is not good if more capabilities are needed with new sw releases and we have always to update the yaml manually

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): latest
- Kubernetes version: (use `kubectl version`): v1.18.8
