### ISSUE TITLE
Consider an e2e-test provider

### ISSUE THREAD

**Issue by micahhausler** [kubernetes-sigs/secrets-store-csi-driver#472]
**Describe the solution you'd like**
In working on #471, I realized it would be really nice to have a dummy provider that was only used for e2e tests in addition to 
the existing e2e tests:

This would be useful for several reasons:
* Testing end-to-end behavior that doesn't need any infrastructure set up (no GCP/Azure/AWS account, no vault installation) 
* Testing eventual API version upgrades from [sigs.k8s.io/secrets-store-csi-driver/provider/v1alpha1](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/provider/v1alpha1/service.proto)
* Verifying plugin behavior when [`RequiresRepublish`](https://kubernetes-csi.github.io/docs/csi-driver-object.html?highlight=RequiresRepublish#what-fields-does-the-csidriver-object-have) is set to `true`

Would this be a contribution the maintainers would like to see?

**Comment by aramase** [comment]
@micahhausler That's a good idea. We already do a mock provider today for running the CSI sanity tests. The mock provider does the mount as part of `NodePublish` and then returns. 

We should also check if there are new tests for `Republish` that have been added as part of the CSI sanity test suite.

**Comment by aramase** [comment]
@tam7t suggested using Kubernetes secret as the backend store for the e2e-test-provider.

**Comment by tam7t** [comment]
I had another discussion today where being able to develop locally i.e. with kind or minikube came up.

If you're trying to develop an application locally and deploying ephemeral/test database to kind/minikube along with your application, you may want to be able to use the CSI driver to configure your pod but provide test creds. Not fetch anything from an external secret store (or have to actually authenticate to an external store). Something like:

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: app-secrets
spec:
  provider: insecure-echo
  parameters:
    secrets: |
      - key: "username"
        value: "localhost-user"
      - key: "password"
        value: "1234"
```
