### ISSUE TITLE
Unbind secret creation from mount action

### ISSUE THREAD

**Issue by dirtycajunrice** [kubernetes-sigs/secrets-store-csi-driver#527]
**Motivation**
Although we would all love to live in a world where every application offered not only the ability to read sensitive credentials via file, but also the ability to reference them on a per file basis, this is simply nowhere near the case in 2021. The propagation of the infamous "12 factor app" has drilled the idealism of environment variable driven configuration regardless of sensitivity level of the value. 

Until the state of affairs shifts to a more security-conscious mentality, the current usage of the csi driver requires multiple additional steps that are of no use other than to "trigger" the action. A user is required to define a completely arbitrary volume and volume mount that will not be consumed in any way by the application. 

**Describe the solution you'd like**
It would be a significant advantage to have the secret creation/deletion flow trigger solely off reference as an environment variable.

Expected:
```yaml
  envFrom:
    - name: my-secret-object
```
Actual:
```yaml
  envFrom:
    - name: my-secret-object
  volumes:
    - name: secrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: some-12-factor-based-app
  volumeMounts:
    - name: secrets
      mountPath: /tmp/literally-doesnt-matter
      readOnly: true
```
