### ISSUE TITLE
Cluster scope + Namespace scope + Renamed kinds

### ISSUE THREAD

**Issue by dirtycajunrice** [kubernetes-sigs/secrets-store-csi-driver#528]
**Motivation**
SecretProviderClass is namespaced and requires duplicated definition of many parameters. Using vault as a first class example, if you have 30 applications with unique distinct secrets within the same vault instance you will define the vaultAddress 30 times, the vaultKubernetesMountPath 30 times, and the roleName _up to_ 30 times depending on configuration.

**Describe the solution you'd like**
I would like to be able to provide an "upstream configuration" for common parameters to reduce toil and redundancy. This becomes more apparent when the names are used in the same fashion that most other x-k8s.io projects are done vs the way they are done here. Using Gateway as an example a GatewayClass would be the Cluster scope, the Gateway would be the namespace scope. Normally a "class" infers a group of things not a single referent.
Proposition:

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-prod
spec:
  provider: vault
  parameters:
    roleName: csi-secrets-store
    vaultAddress: https://vault.company.tld
    vaultKubernetesMountPath: kubernetes/eks-use1-sre-prod
    objects: |
     ...
```

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProvider
metadata:
  name: vault-prod
  namespace: default
spec:
  secretProviderClass: vault-prod
  parameters:
    objects: |
     ...
```
