### ISSUE TITLE
Environment Variables not available from Secrets

### ISSUE THREAD

**Issue by petegrimsdale** [kubernetes-sigs/secrets-store-csi-driver#601]
**What steps did you take and what happened:**
Deployment of CSI driver with simple secrets retrieved from Azure KeyVault.  The secrets have stopped syncing to the environment variables and the Pod fails to start with error message "Error: secret <name of secret> not found"
Failing pod.yml:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-secrets-store-inline
  labels:
    aadpodidbinding: azure-pod-identity-binding-selector # The selector defined in AzureIdentityBinding in the previous step
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: SECRET_DEMO1
        valueFrom:
          secretKeyRef:
            name: demosecret1
            key: demosecret1
      - name: SECRET_DEMO2
        valueFrom:
          secretKeyRef:
            name: demosecret2
            key: demosecret2
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-kvname
```

If the env reference is removed the pods starts correctly with the volumes mounted as expected

**Which provider are you using:**
Azure Key Vault

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
Labels:       app=csi-secrets-store-provider-azure
              app.kubernetes.io/instance=csi-secrets-store-provider-azure-1624294533
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=csi-secrets-store-provider-azure
              app.kubernetes.io/version=0.0.16
              controller-revision-hash=f9b5f8998
              helm.sh/chart=csi-secrets-store-provider-azure-0.0.20

Kubernetes version:  1.19.11

**Comment by nilekhc** [comment]
@petegrimsdale Thank you for opening the issue.
Could you provide your `SecretProviderClass` configuration?

Also, syncSecret is disabled by default in azure provider `v0.0.16`. You need to enable this to install required RBAC. Please refer to [release notes](https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/0.0.16).

**Comment by petegrimsdale** [comment]
@nilekhc - Thanks I was not aware of the breaking change as this is a deployment we have had running from a pipeline for a number of months - let me try with the syncSecret setting enabled

**Comment by ricardotasso** [comment]
@petegrimsdale check if in the secrets-store container in the csi-secrets-store-secrets-store-csi-driver pod aren't you receiving a message related to the Service Account Permission.

I had a similar [issue](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/618) here and was a faulting permission to manage Secrets.

I just added the permission to manage secrets in the Cluster Role 
```
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
 ```
