### ISSUE TITLE
Secrets not rotated when using subPath

### ISSUE THREAD

**Issue by tam7t** [kubernetes-sigs/secrets-store-csi-driver#680]
**Describe the solution you'd like**

When using a volume with `subPath`

```
    volumeMounts:
    - mountPath: /app/spapi/settings.ini
      name: app-config
      subPath: settings.ini
...
  volumes:
  - csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: app-config
    name: app-config
```

The application may not be able to observe when the secret is rotated.

**Anything else you would like to add:**

This may be limited to just the use of the `AtomicWriter` since directly writing the files would not involve symlinks.

We should verify and document this limitation.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
