### ISSUE TITLE
Error: container has runAsNonRoot and image will run as root (container: crds-upgrade)

### ISSUE THREAD

**Issue by pierluigilenoci** [kubernetes-sigs/secrets-store-csi-driver#706]
**What steps did you take and what happened:**

I tried to update the CSI Driver from version 0.0.20 to 0.2.0 and it failed because in our cluster we have a PSP that does not allow it to run as root. 

**What did you expect to happen:**

That container crds-upgrade ran as non-root 

**Anything else you would like to add:**

Our PSP:
```
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
    - 'csi'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
```

The update to version 0.1.0 had failed for #592

**Which provider are you using:**

Not relevant

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): upgrade from chart 0.0.20 to 0.2.0
- Kubernetes version: (use `kubectl version`): v1.20.5
