### ISSUE TITLE
SecretProviderClass returns dict instead of returning each value

### ISSUE THREAD

**Issue by Karabiy** [kubernetes-sigs/secrets-store-csi-driver#795]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
...
Spec:
  Parameters:
    Objects:  - objectName: staging-app
  objectType: "secretsmanager"
  Provider:  aws
  Secret Objects:
    Data:
      Key:          DB_USER_NAME
      Object Name:  staging-app
      Key:          DB_PASSWORD
      Object Name:  staging-app
      Key:          DB_DB_NAME
      Object Name:  staging-app
    Secret Name:    staging-conf
    Type:           Opaque
```
I do have a following SecretProviderClass and when I am trying to get this one as an env variable on the machine, I do receive the following
```bash
echo $DB_DB_NAME 
{"DB_USER_NAME":"username","DB_PASSWORD":"....","DB_DB_NAME":"dbname"}
```
And same for 
```bash
echo $DB_PASSWORD 
{"DB_USER_NAME":"username","DB_PASSWORD":"....","DB_DB_NAME":"dbname"}
```
On the side of the pod
**What did you expect to happen:**
I've expected to receive the key of my, for example: 
```bash
echo $DB_USER_NAME 
username
```
So that I can have a use of it without any changes being applied to my app inside of kubernetes cluster

**Which provider are you using:**
**AWS secrets manager**

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
```yaml
linux:
  enabled: true
  image:
    repository: k8s.gcr.io/csi-secrets-store/driver
    tag: v1.0.0
    pullPolicy: IfNotPresent
  
  crds:
    image:
      repository: k8s.gcr.io/csi-secrets-store/driver-crds
      tag: v1.0.0
      pullPolicy: IfNotPresent
    annotations: {}
```
- Kubernetes version: (use `kubectl version`):
```bash
kubectl version 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```
