### ISSUE TITLE
To mount a secret as an environment variable  I need to mount the whole volume of secrets to the pod (Why!? How better?)

### ISSUE THREAD

**Issue by ovidiubuligan** [kubernetes-sigs/secrets-store-csi-driver#813]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

This is a standard way as per documentation mount secrets as a volume .
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/test/bats/tests/vault/pod-vault-inline-volume-secretproviderclass.yaml

Quite verbose and also mounts all secrets declared in the secretsproviderclass. Eventhough the pod needs only one of those.

Using the secrets as environment variables is nicer since we don't bring all the secrets that the pod doesn't need:
```yaml
spec:
  containers:
  - image: k8s.gcr.io/e2e-test-images/busybox:1.29
    name: busybox
    command:
    - "/bin/sleep"
    - "10000"
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: foosecret
          key: username
```

The pod now only sees one secret that it needs and doesn't expose the rest of them that it doesn't use.

The problem with this is that it doesn't trigger syncing when a new secret is added .
It needs the whole `secrets-store-inline` volume mount besides the Env var secret ref ,and by mounting `secrets-store-inline` , the pod will have access to the whole secretproviderclasse's secrets , which is not good .

How can we solve this without creating combinations of each pod required secrets into secretproviderclasses?
**Environment:**

- Secrets Store CSI Driver version: 1.0.0.:
- Kubernetes version: 1.21:
