### ISSUE TITLE
When using jmesPath secret fails to create

### ISSUE THREAD

**Issue by nathan9120** [kubernetes-sigs/secrets-store-csi-driver#862]
**What steps did you take and what happened:**
When using jmesPath i get this error in the driver log:

``` 
failed to get data in spc for secret" err="file matching objectName username not found in the pod" spc="flux-system/csi-gitlab-secrets" pod="flux-system/csi-secrets-sync-6b6fb94978-2tsg4" secret="flux-system/dummy-consumer-gitlab" spcps="flux-system/csi-secrets-sync-6b6fb94978-2tsg4-flux-system-csi-gitlab-secrets 
```

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: csi-gitlab-secrets
  namespace: flux-system
spec:
  provider: aws
  secretObjects:
    - secretName: dummy-consumer-gitlab
      type: Opaque
      labels:
        provider: "csi-driver"
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password

  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:eu-west-2:XXXXXXXXXX:secret:/my/path/to/dummy-secret-xyz123"
        objectType: "secretsmanager"
        objectAlias: flux-dummy-consumer
        jmesPath:
            - path: "username"
              objectAlias: "username"
            - path: "password"
              objectAlias: "password"
```

aws secret is populated:

```
{
"username":"abc",
"password":"abc123"
}
```

pod deploy:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-secrets-sync
  namespace: flux-system
  labels:
    app: csi-secrets-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-secrets-sync
  template:
    metadata:
      labels:
        app: csi-secrets-sync
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      serviceAccountName: flux-secrets
      containers:
      - name: csi-secrets-sync
        image: kubernetes/pause:latest
        resources:
          limits:
            cpu: 50m
            memory: 32Mi
        volumeMounts:
          - name: secrets-store
            mountPath: "/mnt/secrets-store"
            readOnly: true
        env:
          - name: username
            valueFrom:
              secretKeyRef:
                name: dummy-consumer-gitlab
                key: username
          - name: password
            valueFrom:
              secretKeyRef:
                name: dummy-consumer-gitlab
                key: password
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass:  "csi-gitlab-secrets"

```

**What did you expect to happen:**

I would expect the secret to be mounted with 2 data elements, one for user and one for password.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

When the jmesPath is commented out and the object name is set to the objectAlias i can retrieve the entire json string.

**Which provider are you using:**
[e.g. Azure Key Vault, HashiCorp Vault, etc. Have you checked out the provider's repo for more help?]

aws 

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 0.2.0 (helm deploy)
- Kubernetes version: (use `kubectl version`): 1.21.5
