### ISSUE TITLE
filterWatchSecret enable in the new secretstore version

### ISSUE THREAD

**Issue by lpunati** [kubernetes-sigs/secrets-store-csi-driver#879]
Hello,

We are using secretstore CSI driver. We are using managed identities and those are assigned to VMSS within AKS Cluster and we are using the same MI object ID to reference from the secretproviderclass. We are able to mount the secrets now there is no issue. 
We are not using nodePublishSecretRef in pod.yaml file. I am a bit confused over her why do we need this what is the reason to use this and I am not sure I am not using this and we are able to mount the secrets. The reason now we wanted to check this is we are upgrading secretstore CSI driver version and there is filterwatchsecret enabled by default. will this affect anything in our current workload.  do we need to change anything for this feature or will that not apply in our scenario?
`NOTE: --filtered-watch-secret=true is enabled by default in [v0.1.0](https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.1.0) release. Please take the necessary action to label the nodePublishSecretRef secrets with the secrets-store.csi.k8s.io/used=true label before upgrade.`

There is also one other feature which is syncSecret: enabled: false in new version what does this exactly do can someone point to right direction. As we re using secret objects in our secret provider. does this needs to be true if we need to enable secret rotation?
```
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
    name: dhpaksnpeazureidentity
    namespace: kv
spec:
    type: 0                                 
    resourceID: /s/MI resource ID
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: azure-pod-identity-binding
    namespace: kv
spec:
    azureIdentity: dhpaksnpeazureidentity 
    selector: azure-pod-identity-binding-selector
```

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretproviderclassName }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.secretName }}
      type: Opaque
      # put your appropriate environment and data values
      labels:
        environment: "{{ .Values.secretEnv }}"
      data:
        - objectName: {{ .Values.secretObjectsAlias.objectAlias1 }}
          key: {{ .Values.secretObjectsAlias.objectAlias1 }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "//MI object ID"
    keyvaultName: "//KV name"
    cloudName: ""
    # put your array of secrets
    objects:  |
      array:
        - |
          objectName: {{ .Values.secretObjectsName.objectName1 }}
          objectType: secret  
          objectAlias: {{ .Values.secretObjectsAlias.objectAlias1 }}
          objectVersion: ""
    tenantId: "//tenantid"
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    aadpodidbinding: azure-pod-identity-binding-selector
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: {{ .Values.secretRefName.appsecretName1 }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: {{ .Values.secretObjectsAlias.objectAlias1 }} 
        ports:
        - containerPort: {{ .Values.containerPort }}
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.secretproviderclassName }}
```

Can you please help take a look about the current setup and let us know what are those two fields usage and do we need to change anything in our current setup if we upgrade the version. Thanks.
