### ISSUE TITLE
Ability to create/mount multiple secrets with a set of items not stored anywhere + items being retrieved from external vault store (as it is now)

### ISSUE THREAD

**Issue by dllegru** [kubernetes-sigs/secrets-store-csi-driver#938]
**Describe the solution you'd like**
Currently SSCSI is able to create/mount multiple secrets, keys, and certs **stored** in enterprise-grade external secrets store. 
The feature request is to **add the ability** to SSCSI to **create/mount multiple secrets** with a set of k/v being retrieved from external vault store (as it is now) + other k/v **not stored anywhere**, done ad-hoc in a definition in the `SecretProviderClass`.

**Anything else you would like to add:**
Usecase:

I want to create a k8s secret with a k/v being retrieved from GCP Secret Manager + other k/v not stored anywhere as they are not actually secrets but configuration parameters needed to be in the secret.
I can accomplish the first part easily but can't find a way to create additional k/v's without being referenced in the secret store. 
To give a clear example, this is the `secret` I need to create:
```
apiVersion: v1
kind: Secret
data:
  password: xxxxxxxxxx==
  url: xxxxxxxx=
  username: xxxxx==
metadata:
  name: my-secret-creds
  namespace: my-namespace
type: Opaque
```

This is the original `SecretProviderClass` I'm using to try to accomplish it:
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: argo-cd-repo-server-creds
spec:
  provider: gcp
  secretObjects:
    - secretName: creds-service
      type: Opaque
      data:
        - objectName: secret-password
          key: password
  parameters:
    secrets: |
      - resourceName: "projects/testing-xxxxx/secrets/service-password/versions/latest"
        fileName: "secret-password"

```
Using the above `SecretProviderClass` works fine and I'm able to create the k8s secret, the feature needed is to create other `secretObjects.secretName.data` items that are not being retrieved from `Secret Manager` and being "hard coded" in the SecretProviderClass itself. 

Sort of like this:
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: my-service-server-creds
spec:
  provider: gcp
  secretObjects:
    - secretName: creds-service
      type: Opaque
      data:
        - objectName: secret-password
          key: password
        - objectValue: https://www.my-url.com/ (or perhaps bs64 encoded)
          key: url
        - objectValue: my-username (or perhaps bs64 encoded)
          key: username
  parameters:
    secrets: |
      - resourceName: "projects/testing-xxxxx/secrets/service-password/versions/latest"
        fileName: "secret-password"
```

Right now the only way to overcome this is creating additional items stored in the external secret store in order to generate this final k8s secret with all the values.

In my personal case for example, `argocd` stores connection configuration to fetch repositories in `k8s secrets` . Being my case, I have to create 5 extra non actual secrets (I only need the password in a secret) in order that sscsi is able to build the final secret with all the parameters that `argocd` will use as a config.
