### ISSUE TITLE
Failed to get service account token attrs -- failed to fetch token (forbidden)

### ISSUE THREAD

**Issue by rootd00d** [kubernetes-sigs/secrets-store-csi-driver#939]
**What steps did you take and what happened:**

Using the Azure Kubernetes Service Add-On installation method of CSI Secrets Driver, we're seeing a ton of log items like the following --

```
I0420 18:47:49.633522       1 reconciler.go:227] "reconciler started" spcps="default/nginx-ingress-nginx-controller-58dd7976f4-bwjm5-default-key-vault-foo" controller="rotation"
E0420 18:47:49.637092       1 reconciler.go:229] "failed to reconcile spc for pod" err="failed to get service account token attrs, err: failed to fetch token: serviceaccounts \"nginx-ingress-nginx\" is forbidden: User \"system:serviceaccount:kube-system:aks-secrets-store-csi-driver\" cannot create resource \"serviceaccounts/token\" in API group \"\" in the namespace \"default\"" spc="key-vault-foo" pod="nginx-ingress-nginx-controller-58dd7976f4-bwjm5" controller="rotation"
I0420 18:47:49.637109       1 reconciler.go:233] "reconciler completed" spcps="default/nginx-ingress-nginx-controller-58dd7976f4-bwjm5-default-key-vault-foo" controller="rotation"
```
(Actual key vault name anonymized to "key-vault-foo")

We're using Stakater Reloader to monitor changes to the Kubernetes Secrets that get created and the pods should reload when the value is rotated in Key Vault.  Auto synchronization is enabled on the add-on --

```
  "addonProfiles": {
    "azureKeyvaultSecretsProvider": {
      "config": {
        "enableSecretRotation": "true",
        "rotationPollInterval": "1m"
      },
      "enabled": true,
      "identity": {
        "clientId": "<clientid>",
        "objectId": "<objectid>",
        "resourceId": "<resourceid>"
      }
    },
```

The Kubernetes Secret seems to not be getting updated, and no pods are reloaded.

**What did you expect to happen:**

Expected pods to restart after Secret object is updated -- but the Secret is not getting rotated.

**Anything else you would like to add:**

This seems to start happening after some time.   The only solution was to just delete the Secret to force it to get recreated.

**Which provider are you using:**
AKV

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v1.1.1
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"f74784f1eaf1e02b651778d6ee2df1ae5ee729ae", GitTreeState:"clean", BuildDate:"2022-03-10T07:58:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aramase** [comment]
@rootd00d Thanks for reporting the issue!

As this is specific to the AKS add-on for Secrets Store CSI Driver, I would recommend opening an issue [here](https://github.com/Azure/AKS/issues) so the AKS team can help.

cc @miwithro @ZeroMagic

**Comment by aramase** [comment]
Just to add some context, that error indicates the service account used by the driver is missing the required `ClusterRole` and/or `ClusterRoleBinding` that'll allow it to create a service account token: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/deploy/rbac-secretprovidertokenrequest.yaml. That `ClusterRole` and `ClusterRoleBinding` should be deployed and maintained by AKS as part of the add-on installation.

**Comment by ZeroMagic** [comment]
@aramase  thanks for pointing the bug.

@rootd00d Please try the following mitigation temporarily. The fix in AKS will be contained in next week release.
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aks-secretprovidertokenrequest-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aks-secretprovidertokenrequest-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aks-secretprovidertokenrequest-role
subjects:
- kind: ServiceAccount
  name: aks-secrets-store-csi-driver
  namespace: kube-system
```
create the above objects in your cluster.
