### ISSUE TITLE
Ability to set static secrets under secretObjects

### ISSUE THREAD

**Issue by NickLarsenNZ** [kubernetes-sigs/secrets-store-csi-driver#948]
**Describe the solution you'd like**

I would like to be able to specify some static values that will end up in a secret, along with the secrets that comes from AWS SSM.

For example:

```yml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secrets-provider
spec:
  provider: aws
  secretObjects:
  - secretName: the-secret
    type: Opaque
    data:
    # Non-sensitive values, can be statically set here and visible in the repository
    - key: type
      value: git
    - key: url
      value: https://github.com/my-org
    # sensitive
    - key: githubAppPrivateKey
      objectName: githubAppPrivateKey
  parameters:
    objects: |
      - objectName: "/path/to/githubAppPrivateKey"
        objectType: "ssmparameter"
        objectAlias: "githubAppPrivateKey"
```

**Anything else you would like to add:**

The particular use case is for Argo CD repository credentials. ArgoCD reads K8s secrets natively (without mounting), and does so through labels on the secret. I need to be able to include other values in the secret that aren't actually sensitive, and don't need storing in SSM.

See: <https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repository-credentials>

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): `csi-secrets-store/driver:v1.1.1`
- Kubernetes version: (use `kubectl version`): `v1.21.9`
