### ISSUE TITLE
Secret is not created

### ISSUE THREAD

**Issue by ilyatrub** [kubernetes-sigs/secrets-store-csi-driver#987]
**What steps did you take and what happened:**
I installed Vault and secret-store-csi-driver with Helm charts (managed by ArgoCD) in "vault" namespace (`syncSecret.enabled=true`). In Vault I've done all preparations described in https://learn.hashicorp.com/tutorials/vault/kubernetes-secret-store-driver?in=vault/kubernetes. In "applications" namespace I created a ServiceAccount for application, SecretProviderClass and Deployment. When I apply deployment without referencing a secret in `env`, everything works fine and secrets from Vault are mounted as files in the container. As soon as I'm trying to use `env` referencing secret, which is defined in SercretProviderClass deployment fails with error "secret not found"

**What did you expect to happen:**
Secret to be created, deployment to be successful and env vars are picked up from secret and accessible in the container.

**Anything else you would like to add:**
1. `syncSecret.enabled=true`
2. SecretProviderClass.yaml
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-management
  labels:
    application: app-management
spec:
  provider: vault
  secretObjects:
    - data:
      - key: USER
        objectName: USER
      - key: PASS
        objectName: PASS
      secretName: app-management
      type: Opaque
  parameters:
    vaultAddress: "http://vault.vault.svc:8200"
    roleName: "app_management"
    objects: |
      - objectName: "USER"
        secretPath: "secret/app_management"
        secretKey: "USER"
      - objectName: "PASS"
        secretPath: "secret/app_management"
        secretKey: "PASS"
```
3. Deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-management
  labels:
    application: app-management
spec:
  replicas: 1
  selector:
    matchLabels:
      application: app-management
  template:
    metadata:
      labels:
        application: app-management
    spec:
      serviceAccountName: app-management
      imagePullSecrets:
        - name: registry-creds
      containers:
        - name: app-management
          image: app_management:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-management
          volumeMounts:
            - mountPath: "/secrets"
              name: vault-secrets
              readOnly: true
      volumes:
        - name: vault-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "app-management"
```
4. ServiceAccount.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-management
  labels:
    application: app-management
```
5. Logs from secret-store-csi-driver:
```
I0704 09:03:22.957316       1 exporter.go:35] "initializing metrics backend" backend="prometheus"
I0704 09:03:22.959080       1 main.go:179] starting manager
I0704 09:03:23.059977       1 secrets-store.go:46] "Initializing Secrets Store CSI Driver" driver="secrets-store.csi.k8s.io" version="v1.2.0" buildTime="2022-06-22-17:05"
I0704 09:03:23.060410       1 server.go:120] "Listening for connections" address="//csi/csi.sock"
I0704 09:03:24.365220       1 nodeserver.go:358] node: getting default node info
```
6. Logs from vault-csi-provider:
```
2022-06-24T10:19:02.814Z [INFO]  Creating new gRPC server
2022-06-24T10:19:02.814Z [INFO]  Opening unix socket: endpoint=/provider/vault.sock
2022-06-24T10:19:02.814Z [INFO]  Starting gRPC server
2022-06-24T10:19:02.814Z [INFO]  Starting health handler: addr=:8080
```

**Which provider are you using:**
Vault

**Environment:**

- Secrets Store CSI Driver version: v1.2.0
- Kubernetes version: (use `kubectl version`): v1.22.8
